en:
  blocks.rfcom.name: RF Communication
  blocks.rfcom.init: set pins CE:[CE] CSN:[CSN]
  blocks.rfcom.send: send data [DATA] to address [ADDR]
  blocks.rfcom.listen: listen to [ADDR] address
  blocks.rfcom.stop: stop listening
  blocks.rfcom.available: data available?
  blocks.rfcom.availableLength: available data length
  blocks.rfcom.readString: read String
  blocks.rfcom.readParse: read [TYPE]
  blocks.rfcom.readParseInteger: int
  blocks.rfcom.readParseFloat: float
  blocks.rfcom.channel: set communication channel to [CHANNEL]
  blocks.rfcom.paLevel: set power amplifier level to [LEVEL]
  blocks.rfcom.lessonTitle1: RF Send Data Example
  blocks.rfcom.lessonTitle2: RF Read Data Example

zh-Hans:
  blocks.rfcom.name: RF 通讯
  blocks.rfcom.init: 初始引脚 CE:[CE] CSN:[CSN]
  blocks.rfcom.send: 给 [ADDR] 地址发送数据 [DATA]
  blocks.rfcom.listen: 监听 [ADDR] 地址
  blocks.rfcom.stop: 停止监听
  blocks.rfcom.available: 监听到数据?
  blocks.rfcom.availableLength: 可读取数据长度
  blocks.rfcom.readString: 读取 String
  blocks.rfcom.readParse: 读取 [TYPE]
  blocks.rfcom.readParseInteger: int
  blocks.rfcom.readParseFloat: float
  blocks.rfcom.channel: 将通信频道设为 [CHANNEL]
  blocks.rfcom.paLevel: 将通信功率设为 [LEVEL]
  blocks.rfcom.lessonTitle1: RF 发送数据示例
  blocks.rfcom.lessonTitle2: RF 读取数据示例

zh-Hant:
  blocks.rfcom.name: RF 通訊
  blocks.rfcom.init: 初始引腳 CE:[CE] CSN:[CSN]
  blocks.rfcom.send: 給 [ADDR] 地址發送數據 [DATA]
  blocks.rfcom.listen: 監聽 [ADDR] 地址
  blocks.rfcom.stop: 停止監聽
  blocks.rfcom.available: 監聽到數據?
  blocks.rfcom.availableLength: 可讀取數據長度
  blocks.rfcom.readString: 讀取 String
  blocks.rfcom.readParse: 讀取 [TYPE]
  blocks.rfcom.readParseInteger: int
  blocks.rfcom.readParseFloat: float
  blocks.rfcom.channel: 將通信頻道設為 [CHANNEL]
  blocks.rfcom.paLevel: 將通信功率設為 [LEVEL]
  blocks.rfcom.lessonTitle1: RF 發送數據示例
  blocks.rfcom.lessonTitle2: RF 讀取數據示例
