en:
  blocks.ultrasonic.name: Ultrasonic Ranging
  blocks.ultrasonic.read3pins: pin [PIN] distance(cm)
  blocks.ultrasonic.read4pins: pins ECHO:[ECHO] TRIG:[TRIG] distance(cm)
  blocks.ultrasonic.compensation: set temperature(℃) [TEMP] and humidity(%) [HUM] compensation

zh-Hans:
  blocks.ultrasonic.name: 超声波测距
  blocks.ultrasonic.read3pins: 引脚 [PIN] 距离（cm）
  blocks.ultrasonic.read4pins: 引脚 ECHO:[ECHO] TRIG:[TRIG] 距离（cm）
  blocks.ultrasonic.compensation: 设置温度（℃）[TEMP] 和湿度（%）[HUM] 计算补偿

zh-Hant:
  blocks.ultrasonic.name: 超聲波測距
  blocks.ultrasonic.read3pins: 引腳 [PIN] 距離（cm）
  blocks.ultrasonic.read4pins: 引腳 ECHO:[ECHO] TRIG:[TRIG] 距離（cm）
  blocks.ultrasonic.compensation: 設置溫度（℃）[TEMP] 和濕度（%）[HUM] 計算補償
