en:
  blocks.infraredcom.name: Infrared Communication
  blocks.infraredcom.initReceive: set pin [PIN] to ir receiver
  blocks.infraredcom.eventPolling: receiver events polling
  blocks.infraredcom.whenReceived: when ir received data
  blocks.infraredcom.rawData: raw data
  blocks.infraredcom.receive: command
  blocks.infraredcom.receiveAddr: address
  blocks.infraredcom.protocol: encode protocol
  blocks.infraredcom.initSend: set pin [PIN] to ir sender
  blocks.infraredcom.send: send command [CMD] encode [PROTO]
  blocks.infraredcom.sendAddr: send command:[CMD] address:[ADDR] encode [PROTO]
  blocks.infraredcom.sendRaw: send raw data [RAW] encode [PROTO]

zh-Hans:
  blocks.infraredcom.name: 红外线通讯
  blocks.infraredcom.initReceive: 初始红外接收引脚[PIN]
  blocks.infraredcom.eventPolling: 红外接收事件轮询
  blocks.infraredcom.whenReceived: 当收到红外数据
  blocks.infraredcom.rawData: 原始编码数据
  blocks.infraredcom.receive: 信号
  blocks.infraredcom.receiveAddr: 地址
  blocks.infraredcom.protocol: 编码协议
  blocks.infraredcom.initSend: 初始红外发送引脚[PIN]
  blocks.infraredcom.send: 通过[PROTO]协议发送信号[CMD]
  blocks.infraredcom.sendAddr: 通过[PROTO]协议发送信号:[CMD]地址:[ADDR]
  blocks.infraredcom.sendRaw: 通过[PROTO]协议发送原始编码数据[RAW]

zh-Hant:
  blocks.infraredcom.name: 紅外線通訊
  blocks.infraredcom.initReceive: 初始紅外接收引腳[PIN]
  blocks.infraredcom.eventPolling: 紅外接收事件輪詢
  blocks.infraredcom.whenReceived: 當收到紅外數據
  blocks.infraredcom.rawData: 原始編碼數據
  blocks.infraredcom.receive: 信號
  blocks.infraredcom.receiveAddr: 地址
  blocks.infraredcom.protocol: 編碼協議
  blocks.infraredcom.initSend: 初始紅外發送引腳[PIN]
  blocks.infraredcom.send: 通過[PROTO]協議發送信號[CMD]
  blocks.infraredcom.sendAddr: 通過[PROTO]協議發送信號:[CMD]地址:[ADDR]
  blocks.infraredcom.sendRaw: 通過[PROTO]協議發送原始編碼數據[RAW]
