en:
  blocks.infraredcom.name: Infrared Communication
  blocks.infraredcom.initReceive: set pin [PIN] to ir receiver
  blocks.infraredcom.whenReceived: when ir received
  blocks.infraredcom.receive: command
  blocks.infraredcom.receiveAddr: address
  blocks.infraredcom.receiveText: text String
  blocks.infraredcom.initSend: set pin [PIN] to ir sender
  blocks.infraredcom.send: send command [CMD] encode [PROTO]
  blocks.infraredcom.sendAddr: send command:[CMD] address:[ADDR] encode [PROTO]
  blocks.infraredcom.sendText: send text String [TEXT]

zh-Hans:
  blocks.infraredcom.name: 红外线通讯
  blocks.infraredcom.initReceive: 初始红外接收引脚[PIN]
  blocks.infraredcom.whenReceived: 当收到信号时
  blocks.infraredcom.receive: 信号
  blocks.infraredcom.receiveAddr: 信号地址
  blocks.infraredcom.receiveText: 文本 String
  blocks.infraredcom.initSend: 初始红外发送引脚[PIN]
  blocks.infraredcom.send: 发送[PROTO]协议信号[CMD]
  blocks.infraredcom.sendAddr: 发送[PROTO]协议信号:[CMD]地址:[ADDR]
  blocks.infraredcom.sendText: 发送文本 String [TEXT]

zh-Hant:
  blocks.infraredcom.name: 紅外線通訊
  blocks.infraredcom.initReceive: 初始紅外接收引腳[PIN]
  blocks.infraredcom.whenReceived: 當收到信號時
  blocks.infraredcom.receive: 信號
  blocks.infraredcom.receiveAddr: 信號地址
  blocks.infraredcom.receiveText: 文本 String
  blocks.infraredcom.initSend: 初始紅外發送引腳[PIN]
  blocks.infraredcom.send: 發送[PROTO]協議信號[CMD]
  blocks.infraredcom.sendAddr: 發送[PROTO]協議信號:[CMD]地址:[ADDR]
  blocks.infraredcom.sendText: 發送文本 String [TEXT]
