en:
  blocks.midimusic.name: MIDI Music
  blocks.midimusic.init: set MIDI pin [PIN]
  blocks.midimusic.playDrum: play drum [DRUM] for [BEAT]/4 beats
  blocks.midimusic.playNote: channel [CHAN]play note [NOTE] for [BEAT]/4 beats
  blocks.midimusic.rest: rest for [BEAT]/4 beats
  blocks.midimusic.setInstrument: set channel [CHAN] instrument to [TIMBRE]
  blocks.midimusic.setTimbre: "set channel [CHAN] instrument to expanding timbre # [TIMBRE]"
  blocks.midimusic.setDrum: "set drum timbre type to [TYPE]"
  blocks.midimusic.setVolume: set channel [CHAN] volume to [VOLUME]%
  blocks.midimusic.setAllVolume: set all volume to [VOLUME]%
  blocks.midimusic.setTempo: set tempo to [TEMPO]
  blocks.midimusic.setEqualizer: set channel [CHAN] equalizer [NAME] to [VALUE]
  blocks.midimusic.setReverberation: set channel [CHAN] reverberation [TYPE] volume to [VOLUME]% delay feedback [FEEDBACK]%
  blocks.midimusic.setChorus: set channel [CHAN] chorus [TYPE] volume to [VOLUME]% delay [DELAY] ms
  blocks.midimusic.reset: reset
  blocks.midimusic.drum: 9 (Drum)
  blocks.midimusic.timbre0: "#0 Piano"
  blocks.midimusic.timbre2: "#2 Electric Piano"
  blocks.midimusic.timbre10: "#10 Music Box"
  blocks.midimusic.timbre11: "#11 Vibraphone"
  blocks.midimusic.timbre12: "#12 Marimba"
  blocks.midimusic.timbre15: "#15 Dulcimer"
  blocks.midimusic.timbre19: "#19 Organ"
  blocks.midimusic.timbre22: "#22 Harmonica"
  blocks.midimusic.timbre25: "#25 Guitar"
  blocks.midimusic.timbre27: "#27 Electric Guitar"
  blocks.midimusic.timbre32: "#32 Bass"
  blocks.midimusic.timbre40: "#40 Violin"
  blocks.midimusic.timbre42: "#42 Cello"
  blocks.midimusic.timbre57: "#57 Trombone"
  blocks.midimusic.timbre65: "#65 Saxophone"
  blocks.midimusic.timbre71: "#71 Clarinet"
  blocks.midimusic.timbre73: "#73 Flute"
  blocks.midimusic.timbre79: "#79 Ocarina"
  blocks.midimusic.timbre107: "#107 Zither"
  blocks.midimusic.timbre111: "#111 Surnay"
  blocks.midimusic.timbre114: "#114 Steel Drum"
  blocks.midimusic.drumd2: d2 Snare Drum
  blocks.midimusic.druma2: a2 Bass Drum
  blocks.midimusic.drumcS2: c#2 Side Strike
  blocks.midimusic.drumcS3: c#3 Crash Cymbal
  blocks.midimusic.drumgS2: g#2 Open Hi-Hat
  blocks.midimusic.drumfS2: f#2 Closed Hi-Hat
  blocks.midimusic.drumfS3: f#3 Tambourine
  blocks.midimusic.drumdS2: d#2 Hand Clap
  blocks.midimusic.drumdS5: d#5 Claves
  blocks.midimusic.drumf5: f5 Wood Block
  blocks.midimusic.drumgS3: g#3 Cowbell
  blocks.midimusic.druma5: a5 Triangle
  blocks.midimusic.drumc4: c4 Bongo
  blocks.midimusic.drumdS4: d#4 Conga
  blocks.midimusic.druma4: a4 Cabasa
  blocks.midimusic.drumcS5: c#5 Guiro
  blocks.midimusic.drumaS3: a#3 Vibraslap
  blocks.midimusic.drumaS4: a#4 Maracas
  blocks.midimusic.reverberation0: Room 1
  blocks.midimusic.reverberation1: Room 2
  blocks.midimusic.reverberation2: Room 3
  blocks.midimusic.reverberation3: Hall 1
  blocks.midimusic.reverberation4: Hall 2
  blocks.midimusic.reverberation5: Plate
  blocks.midimusic.reverberation6: Delay
  blocks.midimusic.reverberation7: Panning Delay
  blocks.midimusic.chorus0: Effect 1
  blocks.midimusic.chorus1: Effect 2
  blocks.midimusic.chorus2: Effect 3
  blocks.midimusic.chorus3: Effect 4
  blocks.midimusic.chorus4: Feedback
  blocks.midimusic.chorus5: Flanger-style
  blocks.midimusic.chorus6: Short Delay
  blocks.midimusic.chorus7: Feedback Delay
  blocks.midimusic.lowFrequencyGain: low frequency gain
  blocks.midimusic.mediumLowFrequencyGain: medium low frequency gain
  blocks.midimusic.mediumHighFrequencyGain: medium high frequency gain
  blocks.midimusic.highFrequencyGain: high frequency gain
  blocks.midimusic.lowFrequency: low frequency
  blocks.midimusic.mediumLowFrequency: medium low frequency
  blocks.midimusic.mediumHighFrequency: medium high frequency
  blocks.midimusic.highFrequency: high frequency

zh-Hans:
  blocks.midimusic.name: MIDI 音乐
  blocks.midimusic.init: 初始 MIDI 引脚 [PIN]
  blocks.midimusic.playDrum: 击打 [DRUM] [BEAT]/4 拍
  blocks.midimusic.playNote: 通道 [CHAN] 演奏音符 [NOTE] [BEAT]/4 拍
  blocks.midimusic.rest: 休止 [BEAT]/4 拍
  blocks.midimusic.setInstrument: 将通道 [CHAN] 的乐器设为 [TIMBRE]
  blocks.midimusic.setTimbre: "将通道 [CHAN] 的乐器设为扩展音色 # [TIMBRE]"
  blocks.midimusic.setDrum: 将打击乐音色类型设为 [TYPE]
  blocks.midimusic.setVolume: 将通道 [CHAN] 音量设为 [VOLUME]%
  blocks.midimusic.setAllVolume: 将所有通道音量设为 [VOLUME]%
  blocks.midimusic.setTempo: 将演奏速度设为 [TEMPO]
  blocks.midimusic.setEqualizer: 将通道 [CHAN] 均衡器 [NAME] 设为 [VALUE]
  blocks.midimusic.setReverberation: 将通道 [CHAN] 混音效果 [TYPE] 音量设为 [VOLUME]% 延迟反馈 [FEEDBACK]%
  blocks.midimusic.setChorus: 将通道 [CHAN] 合唱效果 [TYPE] 音量设为 [VOLUME]% 延迟 [DELAY] 毫秒
  blocks.midimusic.reset: 重置
  blocks.midimusic.drum: 9 (打击乐)
  blocks.midimusic.timbre0: "#0 钢琴"
  blocks.midimusic.timbre2: "#2 电钢琴"
  blocks.midimusic.timbre10: "#10 八音盒"
  blocks.midimusic.timbre11: "#11 颤音琴"
  blocks.midimusic.timbre12: "#12 马林巴琴"
  blocks.midimusic.timbre15: "#15 扬琴"
  blocks.midimusic.timbre19: "#19 管风琴"
  blocks.midimusic.timbre22: "#22 口琴"
  blocks.midimusic.timbre25: "#25 吉他"
  blocks.midimusic.timbre27: "#27 电吉他"
  blocks.midimusic.timbre32: "#32 贝斯"
  blocks.midimusic.timbre40: "#40 小提琴"
  blocks.midimusic.timbre42: "#42 大提琴"
  blocks.midimusic.timbre57: "#59 长号"
  blocks.midimusic.timbre65: "#65 萨克斯"
  blocks.midimusic.timbre71: "#71 单簧管"
  blocks.midimusic.timbre73: "#73 长笛"
  blocks.midimusic.timbre79: "#79 陶笛"
  blocks.midimusic.timbre107: "#107 古筝"
  blocks.midimusic.timbre111: "#111 唢呐"
  blocks.midimusic.timbre114: "#114 钢鼓"
  blocks.midimusic.drumd2: d2 军鼓
  blocks.midimusic.druma2: a2 低通鼓
  blocks.midimusic.drumcS2: c#2 边击打
  blocks.midimusic.drumcS3: c#3 碎音镲
  blocks.midimusic.drumgS2: g#2 踏板踩镲
  blocks.midimusic.drumfS2: f#2 闭合踩镲
  blocks.midimusic.drumfS3: f#3 铃鼓
  blocks.midimusic.drumdS2: d#2 拍手
  blocks.midimusic.drumdS5: d#5 响棒
  blocks.midimusic.drumf5: f5 木鱼
  blocks.midimusic.drumgS3: g#3 牛铃
  blocks.midimusic.druma5: a5 三角铁
  blocks.midimusic.drumc4: c4 邦戈鼓
  blocks.midimusic.drumdS4: d#4 康加鼓
  blocks.midimusic.druma4: a4 卡巴萨
  blocks.midimusic.drumcS5: c#5 刮瓜
  blocks.midimusic.drumaS3: a#3 颤音叉
  blocks.midimusic.drumaS4: a#4 沙槌
  blocks.midimusic.reverberation0: 房间 1
  blocks.midimusic.reverberation1: 房间 2
  blocks.midimusic.reverberation2: 房间 3
  blocks.midimusic.reverberation3: 大厅 1
  blocks.midimusic.reverberation4: 大厅 2
  blocks.midimusic.reverberation5: 平台
  blocks.midimusic.reverberation6: 延迟
  blocks.midimusic.reverberation7: 声像延迟
  blocks.midimusic.chorus0: 类型 1
  blocks.midimusic.chorus1: 类型 2
  blocks.midimusic.chorus2: 类型 3
  blocks.midimusic.chorus3: 类型 4
  blocks.midimusic.chorus4: 反馈式
  blocks.midimusic.chorus5: 镶边
  blocks.midimusic.chorus6: 短延迟
  blocks.midimusic.chorus7: 反馈延迟
  blocks.midimusic.lowFrequencyGain: 低频增益
  blocks.midimusic.mediumLowFrequencyGain: 中低频增益
  blocks.midimusic.mediumHighFrequencyGain: 中高频增益
  blocks.midimusic.highFrequencyGain: 高频增益
  blocks.midimusic.lowFrequency: 低频中心频率
  blocks.midimusic.mediumLowFrequency: 中低频中心频率
  blocks.midimusic.mediumHighFrequency: 中高频中心频率
  blocks.midimusic.highFrequency: 高频中心频率

zh-Hant:
  blocks.midimusic.name: MIDI 音樂
  blocks.midimusic.init: 初始 MIDI 引腳 [PIN]
  blocks.midimusic.playDrum: 演奏節拍 [DRUM] [BEAT]/4 拍
  blocks.midimusic.playNote: 通道 [CHAN] 演奏音階 [NOTE] [BEAT]/4 拍
  blocks.midimusic.rest: 演奏休息 [BEAT]/4 拍
  blocks.midimusic.setInstrument: 通道 [CHAN] 的樂器設為 [TIMBRE]
  blocks.midimusic.setTimbre: "通道 [CHAN] 的樂器設為擴展音色 # [TIMBRE]"
  blocks.midimusic.setDrum: 打擊樂音色類型設為 [TYPE]
  blocks.midimusic.setVolume: 通道 [CHAN] 音量設為 [VOLUME]%
  blocks.midimusic.setAllVolume: 所有通道音量設為 [VOLUME]%
  blocks.midimusic.setTempo: 演奏速度設為 [TEMPO]
  blocks.midimusic.setEqualizer: 通道 [CHAN] 均衡器 [NAME] 設為 [VALUE]
  blocks.midimusic.setReverberation: 通道 [CHAN] 混音效果 [TYPE] 音量設為 [VOLUME]% 延遲反饋 [FEEDBACK]%
  blocks.midimusic.setChorus: 通道 [CHAN] 合唱效果 [TYPE] 音量設為 [VOLUME]% 延遲 [DELAY] 毫秒
  blocks.midimusic.reset: 重置
  blocks.midimusic.drum: 9 (打擊樂)
  blocks.midimusic.timbre0: "#0 鋼琴"
  blocks.midimusic.timbre2: "#2 電鋼琴"
  blocks.midimusic.timbre10: "#10 八音盒"
  blocks.midimusic.timbre11: "#11 顫音琴"
  blocks.midimusic.timbre12: "#12 馬林巴琴"
  blocks.midimusic.timbre15: "#15 揚琴"
  blocks.midimusic.timbre19: "#19 管風琴"
  blocks.midimusic.timbre22: "#22 口琴"
  blocks.midimusic.timbre25: "#25 吉他"
  blocks.midimusic.timbre27: "#27 電吉他"
  blocks.midimusic.timbre32: "#32 貝斯"
  blocks.midimusic.timbre40: "#40 小提琴"
  blocks.midimusic.timbre42: "#42 大提琴"
  blocks.midimusic.timbre57: "#59 長號"
  blocks.midimusic.timbre65: "#65 薩克斯"
  blocks.midimusic.timbre71: "#71 單簧管"
  blocks.midimusic.timbre73: "#73 長笛"
  blocks.midimusic.timbre79: "#79 陶笛"
  blocks.midimusic.timbre107: "#107 古箏"
  blocks.midimusic.timbre111: "#111 嗩吶"
  blocks.midimusic.timbre114: "#114 鋼鼓"
  blocks.midimusic.drumd2: d2 軍鼓
  blocks.midimusic.druma2: a2 低通鼓
  blocks.midimusic.drumcS2: c#2 邊擊打
  blocks.midimusic.drumcS3: c#3 碎音鑔
  blocks.midimusic.drumgS2: g#2 踏板踩鑔
  blocks.midimusic.drumfS2: f#2 閉合踩鑔
  blocks.midimusic.drumfS3: f#3 鈴鼓
  blocks.midimusic.drumdS2: d#2 拍手
  blocks.midimusic.drumdS5: d#5 響棒
  blocks.midimusic.drumf5: f5 木魚
  blocks.midimusic.drumgS3: g#3 牛鈴
  blocks.midimusic.druma5: a5 三角鐵
  blocks.midimusic.drumc4: c4 邦戈鼓
  blocks.midimusic.drumdS4: d#4 康加鼓
  blocks.midimusic.druma4: a4 卡巴薩
  blocks.midimusic.drumcS5: c#5 刮瓜
  blocks.midimusic.drumaS3: a#3 顫音叉
  blocks.midimusic.drumaS4: a#4 沙槌
  blocks.midimusic.reverberation0: 房間 1
  blocks.midimusic.reverberation1: 房間 2
  blocks.midimusic.reverberation2: 房間 3
  blocks.midimusic.reverberation3: 大廳 1
  blocks.midimusic.reverberation4: 大廳 2
  blocks.midimusic.reverberation5: 平台
  blocks.midimusic.reverberation6: 延遲
  blocks.midimusic.reverberation7: 聲像延遲
  blocks.midimusic.chorus0: 類型 1
  blocks.midimusic.chorus1: 類型 2
  blocks.midimusic.chorus2: 類型 3
  blocks.midimusic.chorus3: 類型 4
  blocks.midimusic.chorus4: 反饋式
  blocks.midimusic.chorus5: 鑲邊
  blocks.midimusic.chorus6: 短延遲
  blocks.midimusic.chorus7: 反饋延遲
  blocks.midimusic.lowFrequencyGain: 低頻增益
  blocks.midimusic.mediumLowFrequencyGain: 中低頻增益
  blocks.midimusic.mediumHighFrequencyGain: 中高頻增益
  blocks.midimusic.highFrequencyGain: 高頻增益
  blocks.midimusic.lowFrequency: 低頻中心頻率
  blocks.midimusic.mediumLowFrequency: 中低頻中心頻率
  blocks.midimusic.mediumHighFrequency: 中高頻中心頻率
  blocks.midimusic.highFrequency: 高頻中心頻率
