en:
  blocks.leds.name: LED
  blocks.leds.ledState: pin [PIN] LED [STATE]
  blocks.leds.state.on: on
  blocks.leds.state.off: off
  blocks.leds.toggleLed: toggle pin [PIN] LED state
  blocks.leds.brightness: set pin [PIN] LED brightness [LEVEL]
  blocks.leds.trafficLeds.init: set traffic leds red pin [R] yellow pin [Y] green pin [G]
  blocks.leds.trafficLeds.color: set traffic leds [R] red [Y] yellow [G] green
  blocks.leds.rgbLed.init: set RGB LED red pin [R] green pin[G] blue pin [B]
  blocks.leds.rgbLed.color: set RGB LED color [COLOR]
  blocks.leds.rgbLed.off: turn off RGB LED

zh-Hans:
  blocks.leds.name: LED 灯
  blocks.leds.ledState: '[STATE]引脚[PIN] LED 灯'
  blocks.leds.state.on: 开启
  blocks.leds.state.off: 关闭
  blocks.leds.toggleLed: 切换引脚[PIN] LED 灯状态
  blocks.leds.brightness: 将引脚[PIN] LED 灯亮度设为[LEVEL]
  blocks.leds.trafficLeds.init: 初始交通灯绿灯引脚[G]黄灯引脚[Y]红灯引脚[R]
  blocks.leds.trafficLeds.color: 设置交通灯[G]绿灯[Y]黄灯[R]红灯
  blocks.leds.rgbLed.init: 初始 RGB 灯红色引脚[R]绿色引脚[G]蓝色引脚[B]
  blocks.leds.rgbLed.color: 将 RGB 灯颜色设为[COLOR]
  blocks.leds.rgbLed.off: 关闭 RGB 灯

zh-Hant:
  blocks.leds.name: LED 燈
  blocks.leds.ledState: '[STATE]引腳[PIN] LED 燈'
  blocks.leds.state.on: 開啟
  blocks.leds.state.off: 關閉
  blocks.leds.toggleLed: 切換引腳[PIN] LED 燈狀態
  blocks.leds.brightness: 將引腳[PIN] LED 燈亮度設為[LEVEL]
  blocks.leds.trafficLeds.init: 初始交通燈紅燈引腳[R]黃燈引腳[Y]綠燈引腳[G]
  blocks.leds.trafficLeds.color: 設置交通燈[R]紅燈[Y]黃燈[G]綠燈
  blocks.leds.rgbLed.init: 初始 RGB 燈紅色引腳[R]綠色引腳[G]藍色引腳[B]
  blocks.leds.rgbLed.color: 將 RGB 燈顏色設為[COLOR]
  blocks.leds.rgbLed.off: 關閉 RGB 燈
