en:
  blocks.ioexpansion.name: I/O Expansion
  blocks.ioexpansion.addr: set I2C address [ADDR]
  blocks.ioexpansion.setmode: set pin [PIN] mode to [MODE]
  blocks.ioexpansion.inputMode: input
  blocks.ioexpansion.outputMode: output
  blocks.ioexpansion.inputPullUpMode: input pull-up
  blocks.ioexpansion.inputPullDownMode: input pull-down
  blocks.ioexpansion.inputAdcMode: input adc
  blocks.ioexpansion.outputPwmMode: output pwm
  blocks.ioexpansion.setdigital: set digital pin [PIN] to [VALUE]
  blocks.ioexpansion.digitalHigh: high
  blocks.ioexpansion.digitalLow: low
  blocks.ioexpansion.isDigitalHigh: digital pin [PIN] is high?
  blocks.ioexpansion.analogValue: pin [PIN] analog value
  blocks.ioexpansion.percentageValue: pin [PIN] percentage
  blocks.ioexpansion.setfreq: set pwm frequency to [FREQ] Hz
  blocks.ioexpansion.setpwm: set pin [PIN] pwm to [VALUE]
  blocks.ioexpansion.setservo: set pin [PIN] sevro angle to [ANGLE]

zh-Hans:
  blocks.ioexpansion.name: I/O 扩展
  blocks.ioexpansion.addr: 初始 I2C 地址 [ADDR]
  blocks.ioexpansion.setmode: 将引脚 [PIN] 模式设为 [MODE]
  blocks.ioexpansion.inputMode: 输入
  blocks.ioexpansion.outputMode: 输出
  blocks.ioexpansion.inputPullUpMode: 上拉输入
  blocks.ioexpansion.inputPullDownMode: 下拉输入
  blocks.ioexpansion.inputAdcMode: ADC 输入
  blocks.ioexpansion.outputPwmMode: PWM 输出
  blocks.ioexpansion.setdigital: 将数字引脚 [PIN] 设为 [VALUE]
  blocks.ioexpansion.digitalHigh: 高定平
  blocks.ioexpansion.digitalLow: 低电平
  blocks.ioexpansion.isDigitalHigh: 数字引脚 [PIN] 是高电平？
  blocks.ioexpansion.analogValue: 模拟模拟 [PIN] 模拟值
  blocks.ioexpansion.percentageValue: 模拟引脚 [PIN] 百分值
  blocks.ioexpansion.setfreq: 将 PWM 频率设为 [FREQ] Hz
  blocks.ioexpansion.setpwm: 将引脚 [PIN] PWM 占空比设为 [VALUE]
  blocks.ioexpansion.setservo: 将引脚 [PIN] 舵机角度设为 [ANGLE]

zh-Hant:
  blocks.ioexpansion.name: I/O 擴展
  blocks.ioexpansion.addr: 初始 I2C 地址 [ADDR]
  blocks.ioexpansion.setmode: 將引腳 [PIN] 模式設為 [MODE]
  blocks.ioexpansion.inputMode: 輸入
  blocks.ioexpansion.outputMode: 輸出
  blocks.ioexpansion.inputPullUpMode: 上拉輸入
  blocks.ioexpansion.inputPullDownMode: 下拉輸入
  blocks.ioexpansion.inputAdcMode: ADC 輸入
  blocks.ioexpansion.outputPwmMode: PWM 輸出
  blocks.ioexpansion.setdigital: 將數字引腳 [PIN] 設為 [VALUE]
  blocks.ioexpansion.digitalHigh: 高定平
  blocks.ioexpansion.digitalLow: 低電平
  blocks.ioexpansion.isDigitalHigh: 數字引腳 [PIN] 是高電平？
  blocks.ioexpansion.analogValue: 模擬模擬 [PIN] 模擬值
  blocks.ioexpansion.percentageValue: 模擬引腳 [PIN] 百分值
  blocks.ioexpansion.setfreq: 將 PWM 頻率設為 [FREQ] Hz
  blocks.ioexpansion.setpwm: 將引腳 [PIN] PWM 占空比設為 [VALUE]
  blocks.ioexpansion.setservo: 將引腳 [PIN] 舵機角度設為 [ANGLE]
