#pragma once

#define EM_MIDI_TIMBRE_BANK_0 (0)

#define EM_MIDI_TIMBRE_BANK_127 (127)

#define EM_MIDI_TIMBRE_BANK_0_GRAND_PIANO (0)

#define EM_MIDI_TIMBRE_BANK_0_BRIGHT_PIANO (1)

#define EM_MIDI_TIMBRE_BANK_0_ELECTRIC_GRAND_PIANO_3 (2)

#define EM_MIDI_TIMBRE_BANK_0_HONKY_TONK_PIANO (3)

#define EM_MIDI_TIMBRE_BANK_0_ELECTRIC_PIANO_1 (4)

#define EM_MIDI_TIMBRE_BANK_0_ELECTRIC_PIANO_2 (5)

#define EM_MIDI_TIMBRE_BANK_0_HARPSICHORD (6)

#define EM_MIDI_TIMBRE_BANK_0_CLAVI (7)

#define EM_MIDI_TIMBRE_BANK_0_CELESTA (8)

#define EM_MIDI_TIMBRE_BANK_0_GLOCKENSPIEL (9)

#define EM_MIDI_TIMBRE_BANK_0_MUSIC_BOX (10)

#define EM_MIDI_TIMBRE_BANK_0_VIBRAPHONE (11)

#define EM_MIDI_TIMBRE_BANK_0_MARIMBA (12)

#define EM_MIDI_TIMBRE_BANK_0_XYLOPHONE (13)

#define EM_MIDI_TIMBRE_BANK_0_TUBULAR_BELLS (14)

#define EM_MIDI_TIMBRE_BANK_0_DULCIMER (15)

#define EM_MIDI_TIMBRE_BANK_0_DRAWBAR_ORGAN (16)

#define EM_MIDI_TIMBRE_BANK_0_PERCUSSIVE_ORGAN (17)

#define EM_MIDI_TIMBRE_BANK_0_ROCK_ORGAN (18)

#define EM_MIDI_TIMBRE_BANK_0_CHURCH_ORGAN (19)

#define EM_MIDI_TIMBRE_BANK_0_REED_ORGAN (20)

#define EM_MIDI_TIMBRE_BANK_0_ACCORDION_FRENCH (21)

#define EM_MIDI_TIMBRE_BANK_0_HARMONICA (22)

#define EM_MIDI_TIMBRE_BANK_0_TANGO_ACCORDION (23)

#define EM_MIDI_TIMBRE_BANK_0_ACOUSTIC_GUITAR_NYLON_STRING (24)

#define EM_MIDI_TIMBRE_BANK_0_ACOUSTIC_GUITAR_STEEL_STRING (25)

#define EM_MIDI_TIMBRE_BANK_0_ELECTRIC_GUITAR_JAZZ (26)

#define EM_MIDI_TIMBRE_BANK_0_ELECTRIC_GUITAR_CLEAN (27)

#define EM_MIDI_TIMBRE_BANK_0_ELECTRIC_GUITAR_MUTED (28)

#define EM_MIDI_TIMBRE_BANK_0_ELECTRIC_GUITAR_DRIVE (29)

#define EM_MIDI_TIMBRE_BANK_0_ELECTRIC_GUITAR_DISTORTION (30)

#define EM_MIDI_TIMBRE_BANK_0_GUITAR_HARMONICS (31)

#define EM_MIDI_TIMBRE_BANK_0_ACOUSTIC_BASS (32)

#define EM_MIDI_TIMBRE_BANK_0_FINGER_BASS (33)

#define EM_MIDI_TIMBRE_BANK_0_PICKED_BASS (34)

#define EM_MIDI_TIMBRE_BANK_0_FRETLESS_BASS (35)

#define EM_MIDI_TIMBRE_BANK_0_SLAP_BASS_1 (36)

#define EM_MIDI_TIMBRE_BANK_0_SLAP_BASS_2 (37)

#define EM_MIDI_TIMBRE_BANK_0_SYNTH_BASS_1 (38)

#define EM_MIDI_TIMBRE_BANK_0_SYNTH_BASS_2 (39)

#define EM_MIDI_TIMBRE_BANK_0_VIOLIN (40)

#define EM_MIDI_TIMBRE_BANK_0_VIOLA (41)

#define EM_MIDI_TIMBRE_BANK_0_CELLO (42)

#define EM_MIDI_TIMBRE_BANK_0_CONTRABASS (43)

#define EM_MIDI_TIMBRE_BANK_0_TREMOLO_STRINGS (44)

#define EM_MIDI_TIMBRE_BANK_0_PIZZICATO_STRINGS (45)

#define EM_MIDI_TIMBRE_BANK_0_ORCHESTRAL_HARP (46)

#define EM_MIDI_TIMBRE_BANK_0_TIMPANI (47)

#define EM_MIDI_TIMBRE_BANK_0_STRING_ENSEMBLE_1 (48)

#define EM_MIDI_TIMBRE_BANK_0_STRING_ENSEMBLE_2 (49)

#define EM_MIDI_TIMBRE_BANK_0_SYNTH_STRINGS_1 (50)

#define EM_MIDI_TIMBRE_BANK_0_SYNTH_STRINGS_2 (51)

#define EM_MIDI_TIMBRE_BANK_0_CHOIR_AAHS (52)

#define EM_MIDI_TIMBRE_BANK_0_VOICE_OOHS (53)

#define EM_MIDI_TIMBRE_BANK_0_SYNTH_VOICE (54)

#define EM_MIDI_TIMBRE_BANK_0_ORCHESTRA_HIT (55)

#define EM_MIDI_TIMBRE_BANK_0_TRUMPET (56)

#define EM_MIDI_TIMBRE_BANK_0_TROMBONE (57)

#define EM_MIDI_TIMBRE_BANK_0_TUBA (58)

#define EM_MIDI_TIMBRE_BANK_0_MUTED_TRUMPET (59)

#define EM_MIDI_TIMBRE_BANK_0_FRENCH_HORN (60)

#define EM_MIDI_TIMBRE_BANK_0_BRASS_SECTION (61)

#define EM_MIDI_TIMBRE_BANK_0_SYNTH_BRASS_1 (62)

#define EM_MIDI_TIMBRE_BANK_0_SYNTH_BRASS_2 (63)

#define EM_MIDI_TIMBRE_BANK_0_SOPRANO_SAX (64)

#define EM_MIDI_TIMBRE_BANK_0_ALTO_SAX (65)

#define EM_MIDI_TIMBRE_BANK_0_TENOR_SAX (66)

#define EM_MIDI_TIMBRE_BANK_0_BARITONE_SAX (67)

#define EM_MIDI_TIMBRE_BANK_0_OBOE (68)

#define EM_MIDI_TIMBRE_BANK_0_ENGLISH_HORN (69)

#define EM_MIDI_TIMBRE_BANK_0_BASSOON (70)

#define EM_MIDI_TIMBRE_BANK_0_CLARINET (71)

#define EM_MIDI_TIMBRE_BANK_0_PICCOLO (72)

#define EM_MIDI_TIMBRE_BANK_0_FLUTE (73)

#define EM_MIDI_TIMBRE_BANK_0_RECORDER (74)

#define EM_MIDI_TIMBRE_BANK_0_PAN_FLUTE (75)

#define EM_MIDI_TIMBRE_BANK_0_BLOWN_BOTTLE (76)

#define EM_MIDI_TIMBRE_BANK_0_SHAKUHACHI (77)

#define EM_MIDI_TIMBRE_BANK_0_WHISTLE (78)

#define EM_MIDI_TIMBRE_BANK_0_OCARINA (79)

#define EM_MIDI_TIMBRE_BANK_0_SQUARE_LEAD (80)

#define EM_MIDI_TIMBRE_BANK_0_SAWTOOTH_LEAD (81)

#define EM_MIDI_TIMBRE_BANK_0_CALLIOPE_LEAD (82)

#define EM_MIDI_TIMBRE_BANK_0_CHIFF_LEAD (83)

#define EM_MIDI_TIMBRE_BANK_0_CHARANG_LEAD (84)

#define EM_MIDI_TIMBRE_BANK_0_VOICE_LEAD (85)

#define EM_MIDI_TIMBRE_BANK_0_FIFTHS_LEAD (86)

#define EM_MIDI_TIMBRE_BANK_0_BASS_GUITAR_LEAD (87)

#define EM_MIDI_TIMBRE_BANK_0_FANTASIA_PAD (88)

#define EM_MIDI_TIMBRE_BANK_0_WARM_PAD (89)

#define EM_MIDI_TIMBRE_BANK_0_POLY_SYNTH_PAD (90)

#define EM_MIDI_TIMBRE_BANK_0_CHOIR_PAD (91)

#define EM_MIDI_TIMBRE_BANK_0_BOWED_PAD (92)

#define EM_MIDI_TIMBRE_BANK_0_METALLIC_PAD (93)

#define EM_MIDI_TIMBRE_BANK_0_HALO_PAD (94)

#define EM_MIDI_TIMBRE_BANK_0_SWEEP_PAD (95)

#define EM_MIDI_TIMBRE_BANK_0_RAIN_FX (96)

#define EM_MIDI_TIMBRE_BANK_0_SOUND_TRACK_FX (97)

#define EM_MIDI_TIMBRE_BANK_0_CRYSTAL_FX (98)

#define EM_MIDI_TIMBRE_BANK_0_ATMOSPHERE_FX (99)

#define EM_MIDI_TIMBRE_BANK_0_BRIGHTNESS_FX (100)

#define EM_MIDI_TIMBRE_BANK_0_GOBLINS_FX (101)

#define EM_MIDI_TIMBRE_BANK_0_ECHOES_FX (102)

#define EM_MIDI_TIMBRE_BANK_0_SCI_FI_FX (103)

#define EM_MIDI_TIMBRE_BANK_0_SITAR (104)

#define EM_MIDI_TIMBRE_BANK_0_BANJO (105)

#define EM_MIDI_TIMBRE_BANK_0_SHAMISEN (106)

#define EM_MIDI_TIMBRE_BANK_0_KOTO (107)

#define EM_MIDI_TIMBRE_BANK_0_KALIMBA (108)

#define EM_MIDI_TIMBRE_BANK_0_BAGPIPE (109)

#define EM_MIDI_TIMBRE_BANK_0_FIDDLE (110)

#define EM_MIDI_TIMBRE_BANK_0_SHANAI (111)

#define EM_MIDI_TIMBRE_BANK_0_TINKLE_BELL (112)

#define EM_MIDI_TIMBRE_BANK_0_AGOGO (113)

#define EM_MIDI_TIMBRE_BANK_0_STEEL_DRUMS (114)

#define EM_MIDI_TIMBRE_BANK_0_WOODBLOCK (115)

#define EM_MIDI_TIMBRE_BANK_0_TAIKO_DRUM (116)

#define EM_MIDI_TIMBRE_BANK_0_MELODIC_TOM (117)

#define EM_MIDI_TIMBRE_BANK_0_SYNTH_DRUM (118)

#define EM_MIDI_TIMBRE_BANK_0_REVERSE_CYMBAL (119)

#define EM_MIDI_TIMBRE_BANK_0_GUITAR_FRET_NOISE (120)

#define EM_MIDI_TIMBRE_BANK_0_BREATH_NOISE (121)

#define EM_MIDI_TIMBRE_BANK_0_SEASHORE (122)

#define EM_MIDI_TIMBRE_BANK_0_BIRD_TWEET (123)

#define EM_MIDI_TIMBRE_BANK_0_TELEPHONE_RING (124)

#define EM_MIDI_TIMBRE_BANK_0_HELICOPTER (125)

#define EM_MIDI_TIMBRE_BANK_0_APPLAUSE (126)

#define EM_MIDI_TIMBRE_BANK_0_GUN_SHOT (127)

#define EM_MIDI_TIMBRE_BANK_127_PIANO_1 (0)

#define EM_MIDI_TIMBRE_BANK_127_PIANO_2 (1)

#define EM_MIDI_TIMBRE_BANK_127_PIANO_3 (2)

#define EM_MIDI_TIMBRE_BANK_127_DETUNED_ELECTRIC_PIANO_1 (3)

#define EM_MIDI_TIMBRE_BANK_127_ELECTRIC_PIANO_1 (4)

#define EM_MIDI_TIMBRE_BANK_127_ELECTRIC_PIANO_2 (5)

#define EM_MIDI_TIMBRE_BANK_127_DETUNED_ELECTRIC_PIANO_2 (6)

#define EM_MIDI_TIMBRE_BANK_127_HONKY_TONK_PIANO (7)

#define EM_MIDI_TIMBRE_BANK_127_ORGAN_1 (8)

#define EM_MIDI_TIMBRE_BANK_127_ORGAN_2 (9)

#define EM_MIDI_TIMBRE_BANK_127_ORGAN_3 (10)

#define EM_MIDI_TIMBRE_BANK_127_DETUNED_ORGAN_1 (11)

#define EM_MIDI_TIMBRE_BANK_127_CHURCH_ORGAN_2 (12)

#define EM_MIDI_TIMBRE_BANK_127_CHURCH_ORGAN_1 (13)

#define EM_MIDI_TIMBRE_BANK_127_CHURCH_ORGAN_3 (14)

#define EM_MIDI_TIMBRE_BANK_127_ACCORDION_FRENCH (15)

#define EM_MIDI_TIMBRE_BANK_127_HARPSICHORD (16)

#define EM_MIDI_TIMBRE_BANK_127_COUPLED_HARPSICHORD_1 (17)

#define EM_MIDI_TIMBRE_BANK_127_COUPLED_HARPSICHORD_2 (18)

#define EM_MIDI_TIMBRE_BANK_127_CLAVICHORD_1 (19)

#define EM_MIDI_TIMBRE_BANK_127_CLAVICHORD_2 (20)

#define EM_MIDI_TIMBRE_BANK_127_CLAVICHORD_3 (21)

#define EM_MIDI_TIMBRE_BANK_127_CELESTA_1 (22)

#define EM_MIDI_TIMBRE_BANK_127_CELESTA_2 (23)

#define EM_MIDI_TIMBRE_BANK_127_SYNTH_BRASS_1 (24)

#define EM_MIDI_TIMBRE_BANK_127_SYNTH_BRASS_2 (25)

#define EM_MIDI_TIMBRE_BANK_127_SYNTH_BRASS_3 (26)

#define EM_MIDI_TIMBRE_BANK_127_SYNTH_BRASS_4 (27)

#define EM_MIDI_TIMBRE_BANK_127_SYNTH_BASS_1 (28)

#define EM_MIDI_TIMBRE_BANK_127_SYNTH_BASS_2 (29)

#define EM_MIDI_TIMBRE_BANK_127_SYNTH_BASS_3 (30)

#define EM_MIDI_TIMBRE_BANK_127_SYNTH_BASS_4 (31)

#define EM_MIDI_TIMBRE_BANK_127_FANTASIA (32)

#define EM_MIDI_TIMBRE_BANK_127_SYNTH_CALLIOPE (33)

#define EM_MIDI_TIMBRE_BANK_127_CHOIR_AAHS (34)

#define EM_MIDI_TIMBRE_BANK_127_BOWED_GLASS_1 (35)

#define EM_MIDI_TIMBRE_BANK_127_SOUNDTRACK (36)

#define EM_MIDI_TIMBRE_BANK_127_ATMOSPHERE (37)

#define EM_MIDI_TIMBRE_BANK_127_CRYSTAL (38)

#define EM_MIDI_TIMBRE_BANK_127_BAG_PIPE (39)

#define EM_MIDI_TIMBRE_BANK_127_TINKLE_BELL_1 (40)

#define EM_MIDI_TIMBRE_BANK_127_ICE_RAIN_1 (41)

#define EM_MIDI_TIMBRE_BANK_127_OBOE_1 (42)

#define EM_MIDI_TIMBRE_BANK_127_PAN_FLUTE_1 (43)

#define EM_MIDI_TIMBRE_BANK_127_SAW_WAVE (44)

#define EM_MIDI_TIMBRE_BANK_127_CHARANG (45)

#define EM_MIDI_TIMBRE_BANK_127_TUBULAR_BELLS (46)

#define EM_MIDI_TIMBRE_BANK_127_SQUARE_WAVE (47)

#define EM_MIDI_TIMBRE_BANK_127_STRINGS (48)

#define EM_MIDI_TIMBRE_BANK_127_TREMOLO_STRING (49)

#define EM_MIDI_TIMBRE_BANK_127_SLOW_STRINGS (50)

#define EM_MIDI_TIMBRE_BANK_127_PIZZICATO_STRING (51)

#define EM_MIDI_TIMBRE_BANK_127_VIOLIN (52)

#define EM_MIDI_TIMBRE_BANK_127_VIOLA (53)

#define EM_MIDI_TIMBRE_BANK_127_CELLO_1 (54)

#define EM_MIDI_TIMBRE_BANK_127_CELLO_2 (55)

#define EM_MIDI_TIMBRE_BANK_127_CONTRABASS (56)

#define EM_MIDI_TIMBRE_BANK_127_HARP_1 (57)

#define EM_MIDI_TIMBRE_BANK_127_HARP_2 (58)

#define EM_MIDI_TIMBRE_BANK_127_NYLON_STRING_GUITAR (59)

#define EM_MIDI_TIMBRE_BANK_127_STEEL_STRING_GUITAR (60)

#define EM_MIDI_TIMBRE_BANK_127_CHORUS_GUITAR (61)

#define EM_MIDI_TIMBRE_BANK_127_FUNK_GUITAR (62)

#define EM_MIDI_TIMBRE_BANK_127_SITAR (63)

#define EM_MIDI_TIMBRE_BANK_127_ACCORDION_BASS (64)

#define EM_MIDI_TIMBRE_BANK_127_FINGERED_BASS (65)

#define EM_MIDI_TIMBRE_BANK_127_PICKED_BASS (66)

#define EM_MIDI_TIMBRE_BANK_127_FRETLESS_BASS_1 (67)

#define EM_MIDI_TIMBRE_BANK_127_SLAP_BASS_1 (68)

#define EM_MIDI_TIMBRE_BANK_127_SLAP_BASS_2 (69)

#define EM_MIDI_TIMBRE_BANK_127_FRETLESS_BASS_2 (70)

#define EM_MIDI_TIMBRE_BANK_127_FRETLESS_BASS_3 (71)

#define EM_MIDI_TIMBRE_BANK_127_FLUTE_1 (72)

#define EM_MIDI_TIMBRE_BANK_127_FLUTE_2 (73)

#define EM_MIDI_TIMBRE_BANK_127_PICCOLO_1 (74)

#define EM_MIDI_TIMBRE_BANK_127_PICCOLO_2 (75)

#define EM_MIDI_TIMBRE_BANK_127_RECORDER (76)

#define EM_MIDI_TIMBRE_BANK_127_PAN_FLUTE_2 (77)

#define EM_MIDI_TIMBRE_BANK_127_SOPRANO_SAX (78)

#define EM_MIDI_TIMBRE_BANK_127_ALTO_SAX (79)

#define EM_MIDI_TIMBRE_BANK_127_TENOR_SAX (80)

#define EM_MIDI_TIMBRE_BANK_127_BARITONE_SAX (81)

#define EM_MIDI_TIMBRE_BANK_127_CLARINET_1 (82)

#define EM_MIDI_TIMBRE_BANK_127_CLARINET_2 (83)

#define EM_MIDI_TIMBRE_BANK_127_OBOE_2 (84)

#define EM_MIDI_TIMBRE_BANK_127_ENGLISH_HORN (85)

#define EM_MIDI_TIMBRE_BANK_127_BASSOON (86)

#define EM_MIDI_TIMBRE_BANK_127_HARMONICA (87)

#define EM_MIDI_TIMBRE_BANK_127_TRUMPET (88)

#define EM_MIDI_TIMBRE_BANK_127_MUTED_TRUMPET (89)

#define EM_MIDI_TIMBRE_BANK_127_TROMBONE_1 (90)

#define EM_MIDI_TIMBRE_BANK_127_TROMBONE_2 (91)

#define EM_MIDI_TIMBRE_BANK_127_FRENCH_HORN_1 (92)

#define EM_MIDI_TIMBRE_BANK_127_FRENCH_HORN_2 (93)

#define EM_MIDI_TIMBRE_BANK_127_TUBA (94)

#define EM_MIDI_TIMBRE_BANK_127_BRASS_1 (95)

#define EM_MIDI_TIMBRE_BANK_127_BRASS_2 (96)

#define EM_MIDI_TIMBRE_BANK_127_VIBRAPHONE_1 (97)

#define EM_MIDI_TIMBRE_BANK_127_VIBRAPHONE_2 (98)

#define EM_MIDI_TIMBRE_BANK_127_KALIMBA (99)

#define EM_MIDI_TIMBRE_BANK_127_TINKLE_BELL_2 (100)

#define EM_MIDI_TIMBRE_BANK_127_GLOCKENSPIEL (101)

#define EM_MIDI_TIMBRE_BANK_127_TUBULAR_BELL_2 (102)

#define EM_MIDI_TIMBRE_BANK_127_XYLOPHONE (103)

#define EM_MIDI_TIMBRE_BANK_127_MARIMBA (104)

#define EM_MIDI_TIMBRE_BANK_127_KOTO (105)

#define EM_MIDI_TIMBRE_BANK_127_TAISHO_KOTO (106)

#define EM_MIDI_TIMBRE_BANK_127_SHAKUHACHI (107)

#define EM_MIDI_TIMBRE_BANK_127_WHISTLE_1 (108)

#define EM_MIDI_TIMBRE_BANK_127_WHISTLE_2 (109)

#define EM_MIDI_TIMBRE_BANK_127_BLOWN_BOTTLE (110)

#define EM_MIDI_TIMBRE_BANK_127_PAN_FLUTE_3 (111)

#define EM_MIDI_TIMBRE_BANK_127_TIMPANI (112)

#define EM_MIDI_TIMBRE_BANK_127_MELO_TOM_1 (113)

#define EM_MIDI_TIMBRE_BANK_127_MELO_TOM_2 (114)

#define EM_MIDI_TIMBRE_BANK_127_SYNTH_DRUM_1 (115)

#define EM_MIDI_TIMBRE_BANK_127_SYNTH_DRUM_2 (116)

#define EM_MIDI_TIMBRE_BANK_127_TAIKO_1 (117)

#define EM_MIDI_TIMBRE_BANK_127_TAIKO_2 (118)

#define EM_MIDI_TIMBRE_BANK_127_REVERSE_CYMBAL (119)

#define EM_MIDI_TIMBRE_BANK_127_CASTANETS (120)

#define EM_MIDI_TIMBRE_BANK_127_TINKLE_BELL_3 (121)

#define EM_MIDI_TIMBRE_BANK_127_ORCHESTRA_HIT (122)

#define EM_MIDI_TIMBRE_BANK_127_TELEPHONE (123)

#define EM_MIDI_TIMBRE_BANK_127_BIRD (124)

#define EM_MIDI_TIMBRE_BANK_127_HELICOPTER (125)

#define EM_MIDI_TIMBRE_BANK_127_BOWED_GLASS_2 (126)

#define EM_MIDI_TIMBRE_BANK_127_ICE_RAIN_2 (127)
