en:
  blocks.stepmotor.name: 28BYJ-48 Stepper
  blocks.stepmotor.init: set pins INA[INA] INB[INB] INC[INC] IND[IND]
  blocks.stepmotor.rpm: set rpm [RPM]
  blocks.stepmotor.right: turn [IMAGE] around
  blocks.stepmotor.left: turn [IMAGE] around
  blocks.stepmotor.stop: stop
  blocks.stepmotor.turnRightSteps: turn [IMAGE][STEPS] steps
  blocks.stepmotor.turnLeftSteps: turn [IMAGE][STEPS] steps
  blocks.stepmotor.turnRight: turn [IMAGE][DEGREES] degrees
  blocks.stepmotor.turnLeft: trun [IMAGE][DEGREES] degrees
  blocks.stepmotor.turn: turn to [ANGLE] degrees

zh-Hans:
  blocks.stepmotor.name: 28BYJ-48 步进电机
  blocks.stepmotor.init: 初始引腳引脚 INA[INA] INB[INB] INC[INC] IND[IND]
  blocks.stepmotor.rpm: 将转速设为[RPM]RPM
  blocks.stepmotor.right: 连续右转[IMAGE]
  blocks.stepmotor.left: 连续左转[IMAGE]
  blocks.stepmotor.stop: 停止
  blocks.stepmotor.turnRightSteps: 右转[IMAGE][STEPS]步
  blocks.stepmotor.turnLeftSteps: 左转[IMAGE][STEPS]步
  blocks.stepmotor.turnRight: 右转[IMAGE][DEGREES]度
  blocks.stepmotor.turnLeft: 左转[IMAGE][DEGREES]度
  blocks.stepmotor.turn: 转到[ANGLE]度

zh-Hant:
  blocks.stepmotor.name: 28BYJ-48 步進電機
  blocks.stepmotor.init: 初始引腳引腳 INA[INA] INB[INB] INC[INC] IND[IND]
  blocks.stepmotor.rpm: 將轉速設為[RPM]RPM
  blocks.stepmotor.right: 連續右轉[IMAGE]
  blocks.stepmotor.left: 連續左轉[IMAGE]
  blocks.stepmotor.stop: 停止
  blocks.stepmotor.turnRightSteps: 右轉[IMAGE][STEPS]步
  blocks.stepmotor.turnLeftSteps: 左轉[IMAGE][STEPS]步
  blocks.stepmotor.turnRight: 右轉[IMAGE][DEGREES]度
  blocks.stepmotor.turnLeft: 左轉[IMAGE][DEGREES]度
  blocks.stepmotor.turn: 轉到[ANGLE]度
