en:
  blocks.firmata.name: Arduino Firmata
  blocks.firmata.checking: Checking firmware...
  blocks.firmata.firmware: Updating firmware...{progress}%
  blocks.firmata.completed: Updating firmware completed.
  blocks.firmata.readAnalog: read analog [PIN] value
  blocks.firmata.readDigital: read digital [PIN] value
  blocks.firmata.readDistance: Read SONAR trig [PIN_T] echo [PIN_E]
  blocks.firmata.readTemp: read temperature [PIN] value
  blocks.firmata.readHum: read humidity [PIN] value
  blocks.firmata.setPWM: set PWM [PIN] value [VALUE]
  blocks.firmata.setDigital: set digital [PIN] value [VALUE]
  blocks.firmata.writeServo: write servo PIN [PIN] [VALUE] deg
  blocks.firmata.playTone: tone pin [PIN] [FREQUENCY] HZ [DURATION] ms
  blocks.firmata.high: high
  blocks.firmata.low: low

zh-Hans:
  blocks.firmata.name: Arduino Firmata
  blocks.firmata.checking: 检查固件…
  blocks.firmata.firmware: 正在更新固件…{progress}%
  blocks.firmata.completed: 更新固件完成。
  blocks.firmata.readAnalog: 读取模拟口 [PIN] 值
  blocks.firmata.readDigital: 读取数字口 [PIN] 值
  blocks.firmata.readDistance: 读取超声波距离 trig [PIN_T] echo[PIN_E]
  blocks.firmata.readTemp: 读取温度传感器 [PIN] 的温度值
  blocks.firmata.readHum: 读取湿度传感器 [PIN] 的湿度值
  blocks.firmata.setPWM: 设置PWM接口 [PIN] 值为 [VALUE]
  blocks.firmata.setDigital: 设置数字接口 [PIN] 电平状态为 [VALUE]
  blocks.firmata.writeServo: 设置舵机引脚 [PIN] 为 [VALUE] 度
  blocks.firmata.playTone: 设置蜂鸣器引脚 [PIN] 频率为 [FREQUENCY] HZ 时间为 [DURATION] ms
  blocks.firmata.high: 高
  blocks.firmata.low: 低

zh-Hant:
  blocks.firmata.name: Arduino Firmata
  blocks.firmata.checking: 檢查固件…
  blocks.firmata.firmware: 正在更新固件…{progress}%
  blocks.firmata.completed: 更新固件完成。
  blocks.firmata.readAnalog: 讀取模擬口 [PIN] 值
  blocks.firmata.readDigital: 讀取數字口 [PIN] 值
  blocks.firmata.readDistance: 讀取超聲波距離 trig [PIN_T] echo[PIN_E]
  blocks.firmata.readTemp: 讀取溫度傳感器 [PIN] 的溫度值
  blocks.firmata.readHum: 讀取濕度傳感器 [PIN] 的濕度值
  blocks.firmata.setPWM: 設置PWM接口 [PIN] 值為 [VALUE]
  blocks.firmata.setDigital: 設置數字接口 [PIN] 電平狀態為 [VALUE]
  blocks.firmata.writeServo: 設置舵機引腳 [PIN] 為 [VALUE] 度
  blocks.firmata.playTone: 設置蜂鳴器引腳 [PIN] 頻率為 [FREQUENCY] HZ 時間為 [DURATION] ms
  blocks.firmata.high: 高
  blocks.firmata.low: 低
