en:
  blocks.buzzer.name: Buzzer
  blocks.buzzer.activeBuzzer: '[STATE] pin [PIN] active buzzer'
  blocks.buzzer.state.on: on
  blocks.buzzer.state.off: off
  blocks.buzzer.passiveBuzzer: pin [PIN] passive buzzer play note [NOTE] for [BEAT] beats
  blocks.buzzer.playPassiveBuzzer: pin [PIN] passive buzzer play sound [MUSIC] until done
  blocks.buzzer.startPassiveBuzzer: pin [PIN] passive buzzer start sound [MUSIC]
  blocks.buzzer.stopPassiveBuzzer: stop pin [PIN] passive buzzer sound
  blocks.buzzer.music.dadadadum: dadadadum
  blocks.buzzer.music.entertainer: entertainer
  blocks.buzzer.music.prelude: prelude
  blocks.buzzer.music.ode: ode
  blocks.buzzer.music.nyan: nyan
  blocks.buzzer.music.ringtone: ringtone
  blocks.buzzer.music.funk: funk
  blocks.buzzer.music.blues: blues
  blocks.buzzer.music.birthday: birthday
  blocks.buzzer.music.wedding: wedding
  blocks.buzzer.music.funeral: funeral
  blocks.buzzer.music.punchline: punchline
  blocks.buzzer.music.python: python
  blocks.buzzer.music.baddy: baddy
  blocks.buzzer.music.chase: chase
  blocks.buzzer.music.baDing: ba ding
  blocks.buzzer.music.wawawawaa: wawawawaa
  blocks.buzzer.music.jumpUp: jump up
  blocks.buzzer.music.jumpDown: jump down
  blocks.buzzer.music.powerUp: power up
  blocks.buzzer.music.powerDown: power down

zh-Hans:
  blocks.buzzer.name: 蜂鸣器
  blocks.buzzer.activeBuzzer: '[STATE]引脚[PIN]有源蜂鸣器'
  blocks.buzzer.state.on: 开启
  blocks.buzzer.state.off: 关闭
  blocks.buzzer.passiveBuzzer: 引脚[PIN]无源蜂鸣器演奏音符[NOTE][BEAT]拍
  blocks.buzzer.playPassiveBuzzer: 引脚[PIN]无源蜂鸣器播放声音[MUSIC]等待播完
  blocks.buzzer.startPassiveBuzzer: 引脚[PIN]无源蜂鸣器播放声音[MUSIC]
  blocks.buzzer.stopPassiveBuzzer: 停止引脚[PIN]无源蜂鸣器声音
  blocks.buzzer.music.dadadadum: 开场
  blocks.buzzer.music.entertainer: 娱乐
  blocks.buzzer.music.prelude: 前奏
  blocks.buzzer.music.ode: 颂歌
  blocks.buzzer.music.nyan: 初音
  blocks.buzzer.music.ringtone: 铃声
  blocks.buzzer.music.funk: 恐慌
  blocks.buzzer.music.blues: 蓝调
  blocks.buzzer.music.birthday: 生日
  blocks.buzzer.music.wedding: 婚礼
  blocks.buzzer.music.funeral: 葬礼
  blocks.buzzer.music.punchline: 笑点
  blocks.buzzer.music.python: 贪吃蛇
  blocks.buzzer.music.baddy: 坏人
  blocks.buzzer.music.chase: 追逐
  blocks.buzzer.music.baDing: 奖励
  blocks.buzzer.music.wawawawaa: 退场
  blocks.buzzer.music.jumpUp: 跳起来
  blocks.buzzer.music.jumpDown: 跳下去
  blocks.buzzer.music.powerUp: 打开电源
  blocks.buzzer.music.powerDown: 关闭电源


zh-Hant:
  blocks.buzzer.name: 蜂鳴器
  blocks.buzzer.activeBuzzer: '[STATE]引腳[PIN]有源蜂鳴器'
  blocks.buzzer.state.on: 開啟
  blocks.buzzer.state.off: 關閉
  blocks.buzzer.passiveBuzzer: 引腳[PIN]無源蜂鳴器演奏音符[NOTE][BEAT]拍
  blocks.buzzer.playPassiveBuzzer: 引腳[PIN]無源蜂鳴器播放聲音[MUSIC]直到結束
  blocks.buzzer.startPassiveBuzzer: 引腳[PIN]無源蜂鳴器播放聲音[MUSIC]
  blocks.buzzer.stopPassiveBuzzer: 停止引腳[PIN]無源蜂鳴器聲音
  blocks.buzzer.music.dadadadum: 開場
  blocks.buzzer.music.entertainer: 娛樂
  blocks.buzzer.music.prelude: 前奏
  blocks.buzzer.music.ode: 頌歌
  blocks.buzzer.music.nyan: 初音
  blocks.buzzer.music.ringtone: 鈴聲
  blocks.buzzer.music.funk: 恐慌
  blocks.buzzer.music.blues: 藍調
  blocks.buzzer.music.birthday: 生日
  blocks.buzzer.music.wedding: 婚禮
  blocks.buzzer.music.funeral: 葬禮
  blocks.buzzer.music.punchline: 笑點
  blocks.buzzer.music.python: 貪吃蛇
  blocks.buzzer.music.baddy: 壞人
  blocks.buzzer.music.chase: 追逐
  blocks.buzzer.music.baDing: 獎勵
  blocks.buzzer.music.wawawawaa: 退場
  blocks.buzzer.music.jumpUp: 跳起來
  blocks.buzzer.music.jumpDown: 跳下去
  blocks.buzzer.music.powerUp: 打開電源
  blocks.buzzer.music.powerDown: 關閉電源
