en:
  blocks.tracking.name: Tracking
  blocks.tracking.tracking: pin [PIN] sensing black line?
  blocks.tracking.value: pin [PIN] sensing value
  blocks.tracking.threshold: set pin [PIN] sensing value min [NUM1] max [NUM2]
  blocks.tracking.init5: set 5-channel tracker pins SCL [SCL] SDA [SDA]
  blocks.tracking.addr5: set 5-channel tracker I2C address [ADDR]
  blocks.tracking.threshold5: set channel [CHAN] sensing value to [NUM1] to [NUM2]
  blocks.tracking.tracking5: channel [CHAN] sensing black line?
  blocks.tracking.value5: channel [CHAN] sensing value

zh-Hans:
  blocks.tracking.name: 循迹模块
  blocks.tracking.tracking: 引脚[PIN]侦测到黑线？
  blocks.tracking.value: 引脚[PIN]的值
  blocks.tracking.threshold: 将引脚[PIN]阈值设为[NUM1]到[NUM2]
  blocks.tracking.init5: 初始五路循迹引脚 SCL[SCL] SDA[SDA]
  blocks.tracking.addr5: 初始五路循迹 I2C 地址[ADDR]
  blocks.tracking.threshold5: 将第[CHAN]路探头阈值设为[NUM1]到[NUM2]
  blocks.tracking.tracking5: 第[CHAN]路探头侦测到黑线？
  blocks.tracking.value5: 第[CHAN]路探头的值

zh-Hant:
  blocks.tracking.name: 循跡模組
  blocks.tracking.tracking: 引腳[PIN]偵測到黑線？
  blocks.tracking.value: 引腳[PIN]的值
  blocks.tracking.threshold: 將引腳[PIN]閾值設為[NUM1]到[NUM2]
  blocks.tracking.init5: 初始五路循跡引腳 SCL[SCL] SDA[SDA]
  blocks.tracking.addr5: 初始五路循跡 I2C 地址[ADDR]
  blocks.tracking.threshold5: 將第[CHAN]路探頭閾值設為[NUM1]到[NUM2]
  blocks.tracking.tracking5: 第[CHAN]路探頭偵測到黑線？
  blocks.tracking.value5: 第[CHAN]路探頭的值
