en:
  blocks.ld3320asr.name: Speech Recognition
  blocks.ld3320asr.init: set pins SCL:[SCL] SDA:[SDA]
  blocks.ld3320asr.mode: set recognition mode to [MODE]
  blocks.ld3320asr.modeAuto: auto
  blocks.ld3320asr.modeButton: button
  blocks.ld3320asr.modeKeyword: keyword
  blocks.ld3320asr.modeButtonKeyword: button or keyword
  blocks.ld3320asr.setKeyword: set wakeup keyword to [KEYWORD]
  blocks.ld3320asr.setTimeout: set timeout to [MS] ms
  blocks.ld3320asr.eventPolling: recognition events polling
  blocks.ld3320asr.whenRecognized: when recognized [KEYWORD]
  blocks.ld3320asr.lessonTitle1: Simple ASR
  blocks.ld3320asr.lessonTitle2: Button Or Keyword Trigger ASR

zh-Hans:
  blocks.ld3320asr.name: 语音识别
  blocks.ld3320asr.init: 初始引脚 SCL:[SCL] SDA:[SDA]
  blocks.ld3320asr.mode: 初始语音识别模式 [MODE]
  blocks.ld3320asr.modeAuto: 自动
  blocks.ld3320asr.modeButton: 按键
  blocks.ld3320asr.modeKeyword: 关键词
  blocks.ld3320asr.modeButtonKeyword: 按键和关键词
  blocks.ld3320asr.setKeyword: 将唤醒关键词设为 [KEYWORD]
  blocks.ld3320asr.setTimeout: 将识别超时设为 [MS] 毫秒
  blocks.ld3320asr.eventPolling: 语音识别事件轮询
  blocks.ld3320asr.whenRecognized: 当识别到 [KEYWORD] 时
  blocks.ld3320asr.lessonTitle1: 简单语音识别
  blocks.ld3320asr.lessonTitle2: 按键或关键词触发语音识别

zh-Hant:
  blocks.ld3320asr.name: 語音識別
  blocks.ld3320asr.init: 初始引腳 SCL:[SCL] SDA:[SDA]
  blocks.ld3320asr.mode: 初始語音識別模式 [MODE]
  blocks.ld3320asr.modeAuto: 自動
  blocks.ld3320asr.modeButton: 按鍵
  blocks.ld3320asr.modeKeyword: 關鍵詞
  blocks.ld3320asr.modeButtonKeyword: 按鍵和關鍵詞
  blocks.ld3320asr.setKeyword: 將識別關鍵詞設為 [KEYWORD]
  blocks.ld3320asr.setTimeout: 將識別超時設為 [MS] 毫秒
  blocks.ld3320asr.eventPolling: 識別事件輪詢
  blocks.ld3320asr.whenRecognized: 當識別到 [KEYWORD] 時
  blocks.ld3320asr.lessonTitle1: 簡單語音識別
  blocks.ld3320asr.lessonTitle2: 按鍵或關鍵詞觸發語音識別
