en:
  blocks.tuyamqtt.name: Tuya Link
  blocks.tuyamqtt.connect: connect to Tuya MQTT [SERVER] DeviceID:[ID] DeviceSecret:[SECRET]
  blocks.tuyamqtt.isConnected: is connected?
  blocks.tuyamqtt.close: close connection
  blocks.tuyamqtt.servers.china: China Data Center
  blocks.tuyamqtt.servers.centralEurope: Central Europe Data Center
  blocks.tuyamqtt.servers.westernAmerica: Western America Data Center
  blocks.tuyamqtt.servers.easternAmerica: Eastern America Data Center
  blocks.tuyamqtt.servers.westernEurope: Western Europe Data Center
  blocks.tuyamqtt.servers.india: India Data Center
  blocks.tuyamqtt.servers.singapore: Singapore Data Center
  blocks.tuyamqtt.reports: report property [PROP] value [VALUE] by [MODE]
  blocks.tuyamqtt.reportMode.cache: cache
  blocks.tuyamqtt.reportMode.send: send
  blocks.tuyamqtt.whenReceived: when received property values
  blocks.tuyamqtt.propertyValue: property [PROP] value

zh-Hans:
  blocks.tuyamqtt.name: 涂鸦 Link
  blocks.tuyamqtt.connect: 连接到涂鸦 MQTT [SERVER] DeviceID:[ID] DeviceSecret:[SECRET]
  blocks.tuyamqtt.isConnected: 连接成功？
  blocks.tuyamqtt.close: 关闭连接
  blocks.tuyamqtt.servers.china: 中国数据中心
  blocks.tuyamqtt.servers.centralEurope: 中欧数据中心
  blocks.tuyamqtt.servers.westernAmerica: 美西数据中心
  blocks.tuyamqtt.servers.easternAmerica: 美东数据中心
  blocks.tuyamqtt.servers.westernEurope: 西欧数据中心
  blocks.tuyamqtt.servers.india: 印度数据中心
  blocks.tuyamqtt.servers.singapore: 新加坡数据中心
  blocks.tuyamqtt.reports: 上报属性[PROP]值[VALUE]并[MODE]
  blocks.tuyamqtt.reportMode.cache: 缓存
  blocks.tuyamqtt.reportMode.send: 发送
  blocks.tuyamqtt.whenReceived: 当接收下发的属性值时
  blocks.tuyamqtt.propertyValue: 属性[PROP]的值

zh-Hant:
  blocks.tuyamqtt.name: 塗鴉 Link
  blocks.tuyamqtt.connect: 連接到塗鴉 MQTT [SERVER] DeviceID:[ID] DeviceSecret:[SECRET]
  blocks.tuyamqtt.isConnected: 連接成功？
  blocks.tuyamqtt.close: 關閉連接
  blocks.tuyamqtt.servers.china: 中國數據中心
  blocks.tuyamqtt.servers.centralEurope: 中歐數據中心
  blocks.tuyamqtt.servers.westernAmerica: 美西數據中心
  blocks.tuyamqtt.servers.easternAmerica: 美東數據中心
  blocks.tuyamqtt.servers.westernEurope: 西歐數據中心
  blocks.tuyamqtt.servers.india: 印度數據中心
  blocks.tuyamqtt.servers.singapore: 新加坡數據中心
  blocks.tuyamqtt.reports: 上報屬性[PROP]值[VALUE]並[MODE]
  blocks.tuyamqtt.reportMode.cache: 緩存
  blocks.tuyamqtt.reportMode.send: 發送
  blocks.tuyamqtt.whenReceived: 當接收下發的屬性值時
  blocks.tuyamqtt.propertyValue: 屬性[PROP]的值
