en:
  blocks.colors.name: Color Sensor
  blocks.colors.tcs34725: TCS34725 color [RGB] value
  blocks.colors.nlcs11: NLCS11 color [RGB] value
  blocks.colors.red: red
  blocks.colors.green: green
  blocks.colors.blue: blue

zh-Hans:
  blocks.colors.name: 颜色识别
  blocks.colors.tcs34725: TCS34725 颜色 [RGB] 值
  blocks.colors.nlcs11: NLCS11 颜色 [RGB] 值
  blocks.colors.red: 红
  blocks.colors.green: 绿
  blocks.colors.blue: 蓝

zh-Hant:
  blocks.colors.name: 顏色識別
  blocks.colors.tcs34725: TCS34725 顏色 [RGB] 值
  blocks.colors.nlcs11: NLCS11 顏色 [RGB] 值
  blocks.colors.red: 紅
  blocks.colors.green: 綠
  blocks.colors.blue: 藍
