en:
  blocks.colors.name: Color Sensor
  blocks.colors.tcs34725Color: TCS34725 color
  blocks.colors.tcs34725: TCS34725 color [RGB] value
  blocks.colors.nlcs11Color: NLCS11 color
  blocks.colors.nlcs11: NLCS11 color [RGB] value
  blocks.colors.red: r
  blocks.colors.green: g
  blocks.colors.blue: b

zh-Hans:
  blocks.colors.name: 颜色识别
  blocks.colors.tcs34725Color: TCS34725 颜色
  blocks.colors.tcs34725: TCS34725 颜色 [RGB] 值
  blocks.colors.nlcs11Color: NLCS11 颜色
  blocks.colors.nlcs11: NLCS11 颜色 [RGB] 值
  blocks.colors.red: R
  blocks.colors.green: G
  blocks.colors.blue: B

zh-Hant:
  blocks.colors.name: 顏色識別
  blocks.colors.tcs34725Color: TCS34725 顏色
  blocks.colors.tcs34725: TCS34725 顏色 [RGB] 值
  blocks.colors.nlcs11Color: NLCS11 顏色
  blocks.colors.nlcs11: NLCS11 顏色 [RGB] 值
  blocks.colors.red: R
  blocks.colors.green: G
  blocks.colors.blue: B
