en:
  blocks.servo.name: 9g Servo
  blocks.servo.90servo: set PIN [PIN] 90° servo angle to [ANGLE]°
  blocks.servo.180servo: set PIN [PIN] 180° servo angle to [ANGLE]°
  blocks.servo.270servo: set PIN [PIN] 270° servo angle to [ANGLE]°
  blocks.servo.360servo: set PIN [PIN] 360° servo angle to [ANGLE]°
  blocks.servo.motor: set PIN [PIN] 360° motor rotate [ROTATE]
  blocks.servo.motorForward: forward
  blocks.servo.motorReverse: reverse
  blocks.servo.motorStop: stop

zh-Hans:
  blocks.servo.name: 9g 舵机
  blocks.servo.90servo: 将引脚 [PIN] 90°舵机角度设为 [ANGLE]°
  blocks.servo.180servo: 将引脚 [PIN] 180°舵机角度设为 [ANGLE]°
  blocks.servo.270servo: 将引脚 [PIN] 270°舵机角度设为 [ANGLE]°
  blocks.servo.360servo: 将引脚 [PIN] 360°舵机角度设为 [ANGLE]°
  blocks.servo.motor: 将引脚 [PIN] 360°电机转向设为 [ROTATE]
  blocks.servo.motorForward: 正转
  blocks.servo.motorReverse: 反转
  blocks.servo.motorStop: 停止

zh-Hant:
  blocks.servo.name: 9g 舵機
  blocks.servo.90servo: 將引腳 [PIN] 90°舵機角度設為 [ANGLE]°
  blocks.servo.180servo: 將引腳 [PIN] 180°舵機角度設為 [ANGLE]°
  blocks.servo.270servo: 將引腳 [PIN] 270°舵機角度設為 [ANGLE]°
  blocks.servo.360servo: 將引腳 [PIN] 360°舵機角度設為 [ANGLE]°
  blocks.servo.motor: 將引腳 [PIN] 360°電機轉向設為 [ROTATE]
  blocks.servo.motorForward: 正轉
  blocks.servo.motorReverse: 反轉
  blocks.servo.motorStop: 停止
