en:
  blocks.matrix7219.name: MAX7219 Matrix
  blocks.matrix7219.fontCreator: Font Creator
  blocks.matrix7219.fontCreatorLabel: 'Enter the non-English characters(max {count}) to add to the font:'
  blocks.matrix7219.fontCreatorPlaceholder: 'Enter characters...'
  blocks.matrix7219.init: set [ID] device pins CLK:[CLK] CS:[CS] DIN:[DIN]
  blocks.matrix7219.devices: set [ID] device matrix screens [NUM]
  blocks.matrix7219.pixel: set [ID] device [IDX] screen led at x:[X] y:[Y] [STATE]
  blocks.matrix7219.display: display [MATRIX] on [ID] device [IDX] screen
  blocks.matrix7219.text: display [MSG] on [ID] device
  blocks.matrix7219.rotate: rotate [ID] device [IDX] screen to [ANGLE]
  blocks.matrix7219.brightness: set [ID] device [IDX] screen brightness [LEVEL]
  blocks.matrix7219.brightnessall: set [ID] device all screens brightness [LEVEL]
  blocks.matrix7219.clear: clear [IDX] screen on [ID] device
  blocks.matrix7219.clearall: clear all screens on [ID] device
  blocks.matrix7219.stateOn: on
  blocks.matrix7219.stateOff: off

zh-Hans:
  blocks.matrix7219.name: MAX7219 灯点阵
  blocks.matrix7219.fontCreator: 自定义字库
  blocks.matrix7219.fontCreatorLabel: 请输入字库包含的非英文字符（最多 {count} 个）：
  blocks.matrix7219.fontCreatorPlaceholder: 输入字符…
  blocks.matrix7219.init: 初始[ID]设备引脚 CLK:[CLK] CS:[CS] DIN:[DIN]
  blocks.matrix7219.devices: 初始[ID]设备屏数 [NUM]
  blocks.matrix7219.pixel: '[STATE] [ID]设备第[IDX]屏 x:[X] y:[Y] LED'
  blocks.matrix7219.display: 在[ID]设备第[IDX]屏显示[MATRIX]
  blocks.matrix7219.text: 在[ID]设备显示[MSG]
  blocks.matrix7219.rotate: 将[ID]设备第[IDX]屏旋转[ANGLE]
  blocks.matrix7219.brightness: 将[ID]设备第[IDX]屏亮度设为[LEVEL]
  blocks.matrix7219.brightnessall: 将[ID]设备所有屏亮度设为[LEVEL]
  blocks.matrix7219.clear: 清除[ID]设备第[IDX]屏
  blocks.matrix7219.clearall: 清除[ID]设备所有屏
  blocks.matrix7219.stateOn: 开启
  blocks.matrix7219.stateOff: 关闭

zh-Hant:
  blocks.matrix7219.name: MAX7219 燈點陣
  blocks.matrix7219.fontCreator: 生成字庫
  blocks.matrix7219.fontCreatorLabel: 請輸入字庫包含的非英文字符（最多 {count} 個）：
  blocks.matrix7219.fontCreatorPlaceholder: 輸入字符…
  blocks.matrix7219.init: 初始[ID]設備引腳 CLK:[CLK] CS:[CS] DIN:[DIN]
  blocks.matrix7219.devices: 初始[ID]設備屏數 [NUM]
  blocks.matrix7219.pixel: '[STATE] [ID]設備第[IDX]屏 x:[X] y:[Y] LED'
  blocks.matrix7219.display: 在[ID]設備第[IDX]屏顯示[MATRIX]
  blocks.matrix7219.text: 在[ID]設備顯示[MSG]
  blocks.matrix7219.rotate: 將[ID]設備第[IDX]屏旋轉[ANGLE]
  blocks.matrix7219.brightness: 將[ID]設備第[IDX]屏亮度設為[LEVEL]
  blocks.matrix7219.brightnessall: 將[ID]設備所有屏亮度設為[LEVEL]
  blocks.matrix7219.clear: 清除[ID]設備第[IDX]屏
  blocks.matrix7219.clearall: 清除[ID]設備所有屏
  blocks.matrix7219.stateOn: 開啟
  blocks.matrix7219.stateOff: 關閉
