en:
  blocks.vk16k33.name: VK16K33 4-Digit
  blocks.vk16k33.init: set pins SCL[SCL] SDA[SDA]
  blocks.vk16k33.addr: set I2C address [ADDR]
  blocks.vk16k33.display: display number [NUM]
  blocks.vk16k33.time: display time [HH]:[MM]
  blocks.vk16k33.digit: set digit [DIGIT] at [POS]
  blocks.vk16k33.brightness: set brightness [LEVEL]
  blocks.vk16k33.colon: set colon [STATE]
  blocks.vk16k33.state.on: on
  blocks.vk16k33.state.off: off
  blocks.vk16k33.frequency: set blink frequency [FREQ]
  blocks.vk16k33.clear: clear display


zh-Hans:
  blocks.vk16k33.name: VK16K33 四位数码管
  blocks.vk16k33.init: 初始引脚 SCL[SCL] SDA[SDA]
  blocks.vk16k33.addr: 初始 I2C 地址[ADDR]
  blocks.vk16k33.display: 显示数字[NUM]
  blocks.vk16k33.time: 显示时间[HH]:[MM]
  blocks.vk16k33.digit: 将第[POS]位数字设为[DIGIT]
  blocks.vk16k33.brightness: 将亮度设为[LEVEL]
  blocks.vk16k33.colon: '[STATE]冒号'
  blocks.vk16k33.state.on: 开启
  blocks.vk16k33.state.off: 关闭
  blocks.vk16k33.frequency: 将闪烁频率设为[FREQ]
  blocks.vk16k33.clear: 清除显示

zh-Hant:
  blocks.vk16k33.name: VK16K33 四位數碼管
  blocks.vk16k33.init: 初始引腳 SCL[SCL] SDA[SDA]
  blocks.vk16k33.addr: 初始 I2C 地址[ADDR]
  blocks.vk16k33.display: 顯示數字[NUM]
  blocks.vk16k33.time: 顯示時間[HH]:[MM]
  blocks.vk16k33.digit: 將第[POS]位數字設為[DIGIT]
  blocks.vk16k33.brightness: 將亮度設為[LEVEL]
  blocks.vk16k33.colon: '[STATE]冒號'
  blocks.vk16k33.state.on: 開啟
  blocks.vk16k33.state.off: 關閉
  blocks.vk16k33.frequency: 將閃爍頻率設為[FREQ]
  blocks.vk16k33.clear: 清除顯示
