en:
  blocks.switchkey.name: Key Input
  blocks.switchkey.eventPolling: manual button event polling
  blocks.switchkey.whenKey: when pin [PIN] [STATE]
  blocks.switchkey.keyState: pin [PIN] is pressed?
  blocks.switchkey.keyPressed: pressed
  blocks.switchkey.keyClick: click
  blocks.switchkey.keyDoubleClick: doubel click
  blocks.switchkey.keyLongPressed: long pressed
  blocks.switchkey.keyDuringLongPressed: long pressed (during)

zh-Hans:
  blocks.switchkey.name: 按键输入
  blocks.switchkey.eventPolling: 手动按键事件轮询
  blocks.switchkey.whenKey: 当引脚 [PIN] 被 [STATE]
  blocks.switchkey.keyState: 按下引脚 [PIN]？
  blocks.switchkey.keyClick: 单击
  blocks.switchkey.keyDoubleClick: 双击
  blocks.switchkey.keyLongPressed: 长按
  blocks.switchkey.keyDuringLongPressed: 长按（持续）

zh-Hant:
  blocks.switchkey.name: 按鍵輸入
  blocks.switchkey.eventPolling: 手動按鍵事件輪詢
  blocks.switchkey.whenKey: 當引腳 [PIN] 被 [STATE]
  blocks.switchkey.keyState: 按下引腳 [PIN]？
  blocks.switchkey.keyClick: 單擊
  blocks.switchkey.keyDoubleClick: 雙擊
  blocks.switchkey.keyLongPressed: 長按
  blocks.switchkey.keyDuringLongPressed: 長按（持續）
