en:
  blocks.switchkey.name: Key Input
  blocks.switchkey.whenKey: when pin [PIN] [STATE]
  blocks.switchkey.keyState: pin [PIN] is [STATE]?
  blocks.switchkey.keyPressed: pressed
  blocks.switchkey.keyClick: click
  blocks.switchkey.keyDbClick: doubel click
  blocks.switchkey.keyRelease: release
  blocks.switchkey.adcKeyPressed: pin [PIN] adc keyboard [KEY] key is pressed?

zh-Hans:
  blocks.switchkey.name: 按键输入
  blocks.switchkey.whenKey: 当引脚 [PIN] 被 [STATE]
  blocks.switchkey.keyState: 引脚 [PIN] 被 [STATE]？
  blocks.switchkey.keyPressed: 按下
  blocks.switchkey.keyClick: 单击
  blocks.switchkey.keyDbClick: 双击
  blocks.switchkey.keyRelease: 松开
  blocks.switchkey.adcKeyPressed: 按下引脚 [PIN] ADC 按键的 [KEY] 键？

zh-Hant:
  blocks.switchkey.name: 按鍵輸入
  blocks.switchkey.whenKey: 當引腳 [PIN] 被 [STATE]
  blocks.switchkey.keyState: 引腳 [PIN] 被 [STATE]？
  blocks.switchkey.keyPressed: 按下
  blocks.switchkey.keyClick: 單擊
  blocks.switchkey.keyDbClick: 雙擊
  blocks.switchkey.keyRelease: 鬆開
  blocks.switchkey.adcKeyPressed: 按下引腳 [PIN] ADC 按鍵的 [KEY] 鍵？
