en:
  blocks.tm1650.name: TM1650 4-Digit
  blocks.tm1650.init: set pin SCL[SCL] pin SDA[SDA]
  blocks.tm1650.addr: set I2C address [ADDR]
  blocks.tm1650.display: display number [NUM]
  blocks.tm1650.digit: set digit [DIGIT] at [POS]
  blocks.tm1650.brightness: set brightness [LEVEL]
  blocks.tm1650.clear: clear display


zh-Hans:
  blocks.tm1650.name: TM1650 四位数码管
  blocks.tm1650.init: 初始引脚 SCL[SCL] 引脚 SDA[SDA]
  blocks.tm1650.addr: 初始 I2C 地址[ADDR]
  blocks.tm1650.display: 显示数字[NUM]
  blocks.tm1650.digit: 将第[POS]位数字设为[DIGIT]
  blocks.tm1650.brightness: 将亮度设为[LEVEL]
  blocks.tm1650.clear: 清除显示

zh-Hant:
  blocks.tm1650.name: TM1650 四位數碼管
  blocks.tm1650.init: 初始引腳 SCL[SCL] 引腳 SDA[SDA]
  blocks.tm1650.addr: 初始 I2C 地址[ADDR]
  blocks.tm1650.display: 顯示數字[NUM]
  blocks.tm1650.digit: 將第[POS]位數字設為[DIGIT]
  blocks.tm1650.brightness: 將亮度設為[LEVEL]
  blocks.tm1650.clear: 清除顯示
