en:
  blocks.tm1637.name: TM1637 Clock
  blocks.tm1637.init: set pin CLK[CLK] pin DIO[DIO]
  blocks.tm1637.display: display number [NUM]
  blocks.tm1637.time: display time [HH]:[MM]
  blocks.tm1637.digit: set digit [DIGIT] at [POS]
  blocks.tm1637.brightness: set brightness [LEVEL]
  blocks.tm1637.colon: set colon [STATE]
  blocks.tm1637.state.on: on
  blocks.tm1637.state.off: off
  blocks.tm1637.clear: clear display


zh-Hans:
  blocks.tm1637.name: TM1637 时钟数码管
  blocks.tm1637.init: 初始引脚 CLK[CLK] 引脚 DIO[DIO]
  blocks.tm1637.display: 显示数字[NUM]
  blocks.tm1637.time: 显示时间[HH]:[MM]
  blocks.tm1637.digit: 将第[POS]位数字设为[DIGIT]
  blocks.tm1637.brightness: 将亮度设为[LEVEL]
  blocks.tm1637.colon: '[STATE]冒号'
  blocks.tm1637.state.on: 开启
  blocks.tm1637.state.off: 关闭
  blocks.tm1637.clear: 清除显示

zh-Hant:
  blocks.tm1637.name: TM1637 時鐘數碼管
  blocks.tm1637.init: 初始引腳 CLK[CLK] 引腳 DIO[DIO]
  blocks.tm1637.display: 顯示數字[NUM]
  blocks.tm1637.time: 顯示時間[HH]:[MM]
  blocks.tm1637.digit: 將第[POS]位數字設為[DIGIT]
  blocks.tm1637.brightness: 將亮度設為[LEVEL]
  blocks.tm1637.colon: '[STATE]冒號'
  blocks.tm1637.state.on: 開啟
  blocks.tm1637.state.off: 關閉
  blocks.tm1637.clear: 清除顯示
