en:
  blocks.mp3player.name: MP3 Player
  blocks.mp3player.init: set pins TX:[TX] RX:[RX]
  blocks.mp3player.playTrack: play song [TRACK]
  blocks.mp3player.play: play
  blocks.mp3player.pause: pause
  blocks.mp3player.stop: stop
  blocks.mp3player.next: next
  blocks.mp3player.prev: previous
  blocks.mp3player.volume: set volume to [VOL]
  blocks.mp3player.volumeUp: volume up
  blocks.mp3player.volumeDown: volume down
  blocks.mp3player.eq: set equalizer to [EQ]
  blocks.mp3player.eqNormal: normal
  blocks.mp3player.eqPop: pop
  blocks.mp3player.eqRock: rock
  blocks.mp3player.eqJazz: jazz
  blocks.mp3player.eqClassic: classic
  blocks.mp3player.eqBass: bass
  blocks.mp3player.mode: set play mode to [MODE]
  blocks.mp3player.modeLoop: loop
  blocks.mp3player.modeSingleLoop: single loop
  blocks.mp3player.modeShuffle: shuffle

zh-Hans:
  blocks.mp3player.name: MP3 播放器
  blocks.mp3player.init: 初始引脚 TX:[TX] RX:[RX]
  blocks.mp3player.playTrack: 播放曲目 [TRACK]
  blocks.mp3player.play: 播放
  blocks.mp3player.pause: 暂停
  blocks.mp3player.next: 下一首
  blocks.mp3player.prev: 上一首
  blocks.mp3player.stop: 停止
  blocks.mp3player.volume: 将音量设为 [VOL]
  blocks.mp3player.volumeUp: 音量增加
  blocks.mp3player.volumeDown: 音量减少
  blocks.mp3player.eq: 将均衡器设为 [EQ]
  blocks.mp3player.eqNormal: 正常
  blocks.mp3player.eqPop: 流行
  blocks.mp3player.eqRock: 摇滚
  blocks.mp3player.eqJazz: 爵士
  blocks.mp3player.eqClassic: 古典
  blocks.mp3player.eqBass: 低音
  blocks.mp3player.mode: 将播放模式设为 [MODE]
  blocks.mp3player.modeLoop: 全部循环
  blocks.mp3player.modeSingleLoop: 单曲循环
  blocks.mp3player.modeShuffle: 随机

zh-Hant:
  blocks.mp3player.name: MP3 播放器
  blocks.mp3player.init: 初始引腳 TX:[TX] RX:[RX]
  blocks.mp3player.playTrack: 播放曲目 [TRACK]
  blocks.mp3player.play: 播放
  blocks.mp3player.pause: 暫停
  blocks.mp3player.next: 下一首
  blocks.mp3player.prev: 上一首
  blocks.mp3player.stop: 停止
  blocks.mp3player.volume: 將音量設為 [VOL]
  blocks.mp3player.volumeUp: 音量增加
  blocks.mp3player.volumeDown: 音量減少
  blocks.mp3player.eq: 將均衡器設為 [EQ]
  blocks.mp3player.eqNormal: 正常
  blocks.mp3player.eqPop: 流行
  blocks.mp3player.eqRock: 搖滾
  blocks.mp3player.eqJazz: 爵士
  blocks.mp3player.eqClassic: 古典
  blocks.mp3player.eqBass: 低音
  blocks.mp3player.mode: 將播放模式設為 [MODE]
  blocks.mp3player.modeLoop: 全部循環
  blocks.mp3player.modeSingleLoop: 單曲循環
  blocks.mp3player.modeShuffle: 隨機
