en:
  blocks.c2mqtt.name: ESP32C2 MQTT
  blocks.c2mqtt.lessonTitle: ESP32C2 MQTT Exmple
  blocks.c2mqtt.wifi: connect to wifi ssid:[SSID] password:[PWD]
  blocks.c2mqtt.userConfig: config MQTT username:[USER] password:[PWD] client id:[ID] connection:[SCHEME]
  blocks.c2mqtt.connect: connect to MQTT server:[SERVER] port:[PORT]
  blocks.c2mqtt.publish: publish message [MSG] to the topic [TOPIC] QoS [QOS]
  blocks.c2mqtt.subscribe: subscribes to topic [TOPIC] QoS [QOS]
  blocks.c2mqtt.polling: subscribes events polling
  blocks.c2mqtt.whenTopic: when received for topic [TOPIC]
  blocks.c2mqtt.message: message content
  blocks.c2mqtt.topic1: topic 1
  blocks.c2mqtt.message1: message 1
  blocks.c2mqtt.qos0: most once
  blocks.c2mqtt.qos1: least once
  blocks.c2mqtt.qos2: exactly once

zh-Hans:
  blocks.c2mqtt.name: ESP32C2 MQTT
  blocks.c2mqtt.lessonTitle: ESP32C2 MQTT 案例
  blocks.c2mqtt.wifi: 连接到 WiFi SSID:[SSID] 密码:[PWD]
  blocks.c2mqtt.userConfig: 配置 MQTT 服务用户名:[USER] 密码:[PWD] 客户端ID:[ID] 连接方式:[SCHEME]
  blocks.c2mqtt.connect: 连接到 MQTT 服务器:[SERVER] 端口号:[PORT]
  blocks.c2mqtt.publish: 发布消息 [MSG] 给主题 [TOPIC] QoS [QOS]
  blocks.c2mqtt.subscribe: 订阅主题 [TOPIC] QoS [QOS]
  blocks.c2mqtt.polling: 订阅事件轮询
  blocks.c2mqtt.whenTopic: 当收到主题 [TOPIC] 的消息
  blocks.c2mqtt.message: 消息内容
  blocks.c2mqtt.topic1: 主题1
  blocks.c2mqtt.message1: 消息1
  blocks.c2mqtt.qos0: 最多1次
  blocks.c2mqtt.qos1: 至少1次
  blocks.c2mqtt.qos2: 仅1次

zh-Hant:
  blocks.c2mqtt.name: ESP32C2 MQTT
  blocks.c2mqtt.lessonTitle: ESP32C2 MQTT 案例
  blocks.c2mqtt.wifi: 連接到 WiFi SSID:[SSID] 密碼:[PWD]
  blocks.c2mqtt.userConfig: 配置 MQTT 服務用戶名:[USER] 密碼:[PWD] 客戶端ID:[ID] 連接方式:[SCHEME]
  blocks.c2mqtt.connect: 連接到 MQTT 服務器:[SERVER] 端口號:[PORT]
  blocks.c2mqtt.publish: 發布消息 [MSG] 給主題 [TOPIC] QoS [QOS]
  blocks.c2mqtt.subscribe: 訂閱主題 [TOPIC] QoS [QOS]
  blocks.c2mqtt.polling: 訂閱事件輪詢
  blocks.c2mqtt.whenTopic: 當收到主題 [TOPIC] 的消息
  blocks.c2mqtt.message: 消息內容
  blocks.c2mqtt.topic1: 主題1
  blocks.c2mqtt.message1: 消息1
  blocks.c2mqtt.qos0: 最多1次
  blocks.c2mqtt.qos1: 至少1次
  blocks.c2mqtt.qos2: 僅1次
