en:
  blocks.ainput.name: Analog Values
  blocks.ainput.rawValue: pin [PIN] raw value
  blocks.ainput.percentage: pin [PIN] percentage (0~100)
  blocks.ainput.joystick: pin [PIN] joystick (-100~100)
  blocks.ainput.voltage: pin [PIN] voltage #, reference [REF]


zh-Hans:
  blocks.ainput.name: 模拟值转换
  blocks.ainput.rawValue: 引脚[PIN]原始模拟值
  blocks.ainput.percentage: 引脚[PIN]百分比（0~100）
  blocks.ainput.joystick: 引脚[PIN]摇杆值（-100~100）
  blocks.ainput.voltage: 引脚[PIN]电压 #，参考电压[REF]

zh-Hant:
  blocks.ainput.name: 模擬值轉換
  blocks.ainput.rawValue: 引腳[PIN]原始模擬值
  blocks.ainput.percentage: 引腳[PIN]百分比（0~100）
  blocks.ainput.joystick: 引腳[PIN]搖杆值（-100~100）
  blocks.ainput.voltage: 引腳[PIN]電壓 #，參考電壓[REF]
