en:
  blocks.md40motor.name: MD40 Encoder Motor Board
  blocks.md40motor.addr: set I2C address [ADDR]
  blocks.md40motor.init: set [MOTOR] encoder motor to ratio [RATIO] [PULSE] ppr and [PHASE] phase leads
  blocks.md40motor.all: all
  blocks.md40motor.forward: forward
  blocks.md40motor.reverse: reverse
  blocks.md40motor.setspeed: set [MOTOR] encoder motor to [SPEED]% [DIR] speed
  blocks.md40motor.setrpm: set [MOTOR] encoder motor to [DIR] at [RPM] rpm
  blocks.md40motor.setrotate: rotate [MOTOR] encoder motor to [DEGREE]° at [RPM] rpm
  blocks.md40motor.setangle: set [MOTOR] encoder motor to [ANGLE]° at [RPM] rpm
  blocks.md40motor.reset: reset [MOTOR] encoder motor
  blocks.md40motor.shutdown: stop [MOTOR] encoder motor
  blocks.md40motor.setpidangle: set [MOTOR] encoder motor to P:[P] I:[I] D:[D] for angle pid controller
  blocks.md40motor.setpidspeed: set [MOTOR] encoder motor to P:[P] I:[I] D:[D] fro speed pid controller
  blocks.md40motor.speed: "[MOTOR] encoder motor speed(%)"
  blocks.md40motor.rpm: "[MOTOR] encoder motor rpm"
  blocks.md40motor.angle: "[MOTOR] encoder motor angle"
  blocks.md40motor.pulse: "[MOTOR] encoder motor pulses"
  blocks.md40motor.pidangle: "[MOTOR] encoder motor angle pid controller [PID] value"
  blocks.md40motor.pidspeed: "[MOTOR] encoder motor speed pid controller [PID] value"
  blocks.md40motor.state: "[MOTOR] encoder motor [STATE]?"
  blocks.md40motor.stateIdle: idle
  blocks.md40motor.stateRunning: running
  blocks.md40motor.stateReached: done
  blocks.md40motor.run: set [MOTOR] motor to [SPEED]% [DIR] speed
  blocks.md40motor.stop: stop [MOTOR] motor

zh-Hans:
  blocks.md40motor.name: MD40 编码电机驱动板
  blocks.md40motor.addr: 初始 I2C 地址 [ADDR]
  blocks.md40motor.init: 初始 [MOTOR] 编码电机减速比 [RATIO] [PULSE] 脉冲/转 [PHASE] 相领先
  blocks.md40motor.all: 全部
  blocks.md40motor.forward: 正转
  blocks.md40motor.reverse: 反转
  blocks.md40motor.setspeed: 将 [MOTOR] 编码电机 [DIR] 速度设为 [SPEED]%
  blocks.md40motor.setrpm: 将 [MOTOR] 编码电机 [DIR] 速度设为 [RPM] RPM
  blocks.md40motor.setrotate: 将 [MOTOR] 编码电机以 [RPM] RPM 速度转 [DEGREE]°
  blocks.md40motor.setangle: 将 [MOTOR] 编码电机以 [RPM] RPM 速度转到 [ANGLE]°
  blocks.md40motor.reset: 重置 [MOTOR] 编码电机
  blocks.md40motor.shutdown: 停止 [MOTOR] 编码电机
  blocks.md40motor.setpidangle: 将 [MOTOR] 编码电机角度 PID 控制器参数设为 P:[P] I:[I] D:[D]
  blocks.md40motor.setpidspeed: 将 [MOTOR] 编码电机速度 PID 控制器参数设为 P:[P] I:[I] D:[D]
  blocks.md40motor.speed: "[MOTOR] 编码电机速度（%）"
  blocks.md40motor.rpm: "[MOTOR] 编码电机速度（RPM）"
  blocks.md40motor.angle: "[MOTOR] 编码电机角度"
  blocks.md40motor.pulse: "[MOTOR] 编码电机脉冲数"
  blocks.md40motor.pidangle: "[MOTOR] 编码电机角度 PID 控制器 [PID] 值"
  blocks.md40motor.pidspeed: "[MOTOR] 编码电机速度 PID 控制器 [PID] 值"
  blocks.md40motor.state: "[MOTOR] 编码电机 [STATE]？"
  blocks.md40motor.stateIdle: 空闲
  blocks.md40motor.stateRunning: 运行
  blocks.md40motor.stateReached: 完成
  blocks.md40motor.run: 将 [MOTOR] 电机 [DIR] 速度设为 [SPEED]%
  blocks.md40motor.stop: 停止 [MOTOR] 电机

zh-Hant:
  blocks.md40motor.name: MD40 編碼電機驅動板
  blocks.md40motor.addr: 初始 I2C 地址 [ADDR]
  blocks.md40motor.init: 初始 [MOTOR] 編碼電機減速比 [RATIO] [PULSE] 脈衝/轉 [PHASE] 相領先
  blocks.md40motor.all: 全部
  blocks.md40motor.forward: 正轉
  blocks.md40motor.reverse: 反轉
  blocks.md40motor.setspeed: 將 [MOTOR] 編碼電機 [DIR] 速度設為 [SPEED]%
  blocks.md40motor.setrpm: 將 [MOTOR] 編碼電機 [DIR] 速度設為 [RPM] RPM
  blocks.md40motor.setrotate: 將 [MOTOR] 編碼電機以 [RPM] RPM 速度轉 [DEGREE]°
  blocks.md40motor.setangle: 將 [MOTOR] 編碼電機以 [RPM] RPM 速度轉到 [ANGLE]°
  blocks.md40motor.reset: 重置 [MOTOR] 編碼電機
  blocks.md40motor.shutdown: 停止 [MOTOR] 編碼電機
  blocks.md40motor.setpidangle: 將 [MOTOR] 編碼電機角度 PID 控制器參數設為 P:[P] I:[I] D:[D]
  blocks.md40motor.setpidspeed: 將 [MOTOR] 編碼電機速度 PID 控制器參數設為 P:[P] I:[I] D:[D]
  blocks.md40motor.speed: "[MOTOR] 編碼電機速度（%）"
  blocks.md40motor.rpm: "[MOTOR] 編碼電機速度（RPM）"
  blocks.md40motor.angle: "[MOTOR] 編碼電機角度"
  blocks.md40motor.pulse: "[MOTOR] 編碼電機脈衝數"
  blocks.md40motor.pidangle: "[MOTOR] 編碼電機角度 PID 控制器 [PID] 值"
  blocks.md40motor.pidspeed: "[MOTOR] 編碼電機速度 PID 控制器 [PID] 值"
  blocks.md40motor.state: "[MOTOR] 編碼電機 [STATE]？"
  blocks.md40motor.stateIdle: 空閒
  blocks.md40motor.stateRunning: 運行
  blocks.md40motor.stateReached: 完成
  blocks.md40motor.run: 將 [MOTOR] 電機 [DIR] 速度設為 [SPEED]%
  blocks.md40motor.stop: 停止 [MOTOR] 電機
