en:
  blocks.websocket.name: WebSocket
  blocks.websocket.connect: connect to [URL]
  blocks.websocket.send: send message [MESSAGE]
  blocks.websocket.whenMessageReceived: when message received
  blocks.websocket.receivedText: received text message
  blocks.websocket.receivedJSON: item [PATH] of received JSON data
  blocks.websocket.whenConnected: when connected to WebSocket server
  blocks.websocket.isConnected: is connected?
  blocks.websocket.whenConnectionErrors: when connection errors
  blocks.websocket.isConnectionErrored: is connection errored?
  blocks.websocket.whenConnectionCloses: when connection closes
  blocks.websocket.isConnectionClosed: is connection cloased?
  blocks.websocket.closeConnection: close connection

zh-Hans:
  blocks.websocket.name: WebSocket
  blocks.websocket.connect: 连接到 [URL]
  blocks.websocket.send: 发送消息 [MESSAGE]
  blocks.websocket.whenMessageReceived: 当接收到消息
  blocks.websocket.receivedText: 文本消息
  blocks.websocket.receivedJSON: JSON 数据路径 [PATH] 的项
  blocks.websocket.whenConnected: 当连接到 WebSocket 服务器
  blocks.websocket.isConnected: 连接成功？
  blocks.websocket.whenConnectionErrors: 当连接发生错误
  blocks.websocket.isConnectionErrored: 连接发生错误？
  blocks.websocket.whenConnectionCloses: 当连接关闭
  blocks.websocket.isConnectionClosed: 连接关闭？
  blocks.websocket.closeConnection: 关闭连接

zh-Hant:
  blocks.websocket.name: WebSocket
  blocks.websocket.connect: 連接到 [URL]
  blocks.websocket.send: 發送消息 [MESSAGE]
  blocks.websocket.whenMessageReceived: 當接收到消息
  blocks.websocket.receivedText: 文本消息
  blocks.websocket.receivedJSON: JSON 數據路徑 [PATH] 的項
  blocks.websocket.whenConnected: 當連接到 WebSocket 服務器
  blocks.websocket.isConnected: 連接成功？
  blocks.websocket.whenConnectionErrors: 當連接發生錯誤
  blocks.websocket.isConnectionErrored: 連接發生錯誤？
  blocks.websocket.whenConnectionCloses: 當連接關閉
  blocks.websocket.isConnectionClosed: 連接關閉？
  blocks.websocket.closeConnection: 關閉連接
