en:
  blocks.rfidrc522.name: RFID
  blocks.rfidrc522.whennewcard: when a new card
  blocks.rfidrc522.write: write data [HEX] to card block [BLOCK]
  blocks.rfidrc522.cardid: card id
  blocks.rfidrc522.data: card data

zh-Hans:
  blocks.rfidrc522.name: RFID 模组
  blocks.rfidrc522.whennewcard: 当感应到卡片时
  blocks.rfidrc522.write: 将数据 [HEX] 写入卡片 [BLOCK] 数据块
  blocks.rfidrc522.cardid: 卡片 ID
  blocks.rfidrc522.data: 卡片数据

zh-Hant:
  blocks.rfidrc522.name: RFID 模組
  blocks.rfidrc522.whennewcard: 當感應到卡片時
  blocks.rfidrc522.write: 將數據 [HEX] 寫入卡片 [BLOCK] 數據塊
  blocks.rfidrc522.cardid: 卡片 ID
  blocks.rfidrc522.data: 卡片數據
